import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import { requireRole } from "../../../middleware/role-guard.js";
import { PostgresIdentityUnavailableError, requirePostgresIdentityForSubject } from "../../../platform/postgres-identities.js";
import { decideLegalHoldChange, proposeLegalHoldChange, readDistributionLegalHoldLifecycle, SupportEvidenceLifecycleError } from "../../../platform/postgres-support-evidence-lifecycle.js";
import { decideOrganizationDocumentDisposition, listOrganizationDocumentsForLifecycle, OrganizationDocumentLifecycleError, proposeOrganizationDocumentDisposition, readOrganizationDocumentLifecycle } from "../../../platform/postgres-organization-document-lifecycle.js";
import { HttpError } from "../../../utils/errors.js";
import { readCommandId } from "../../../utils/idempotency.js";

const uuid=z.string().uuid();
const documentParams=z.object({documentId:uuid});
const requestParams=z.object({requestId:uuid});
const listQuery=z.object({status:z.enum(["active","archived"]).optional(),limit:z.coerce.number().int().min(1).max(200).default(100)});
const holdBody=z.object({scope:z.enum(["document","organization"]),changeType:z.enum(["impose","release"]),reasonCategory:z.enum(["litigation","regulatory_request","audit","investigation","complaint","security_incident"]),reason:z.string().trim().min(20).max(2000)});
const dispositionBody=z.object({reason:z.string().trim().min(20).max(2000)});
const decisionBody=z.object({decision:z.enum(["approve","reject"]),decisionReason:z.string().trim().min(20).max(2000)});
const distributionTargetType=z.enum(["distribution_declaration","distribution_payout_exception","distribution_tax_remittance"]);
const distributionTargetParams=z.object({targetType:distributionTargetType,targetId:uuid});
const distributionHoldBody=z.object({changeType:z.enum(["impose","release"]),reasonCategory:z.enum(["litigation","regulatory_request","audit","investigation","complaint","security_incident"]),reason:z.string().trim().min(20).max(2000)});
const commandHeaders={type:"object",required:["x-command-id"],properties:{"x-command-id":{type:"string",minLength:1,maxLength:200}}} as const;
const idParams={type:"object",additionalProperties:false,required:["documentId"],properties:{documentId:{type:"string",format:"uuid"}}} as const;
const requestIdParams={type:"object",additionalProperties:false,required:["requestId"],properties:{requestId:{type:"string",format:"uuid"}}} as const;
const actorJson={type:"object",additionalProperties:false,required:["id","legalName"],properties:{id:{type:"string",format:"uuid"},legalName:{type:"string"}}} as const;
const nullableDateJson={anyOf:[{type:"string",format:"date-time"},{type:"null"}]} as const;
const documentSummaryJson={type:"object",additionalProperties:false,required:["id","organizationId","title","status","retentionBindingStatus","retainUntil","retentionElapsed","versionCount","dispositionStatus"],properties:{id:{type:"string",format:"uuid"},organizationId:{type:"string",format:"uuid"},title:{type:"string"},status:{type:"string",enum:["active","archived"]},retentionBindingStatus:{type:"string",enum:["legacy_declared","governed"]},retainUntil:{type:"string",format:"date-time"},retentionElapsed:{type:"boolean"},versionCount:{type:"integer",minimum:1},dispositionStatus:{anyOf:[{type:"string",enum:["cleanup_requested","completed","failed"]},{type:"null"}]}}} as const;
const holdTargetTypes=["identity","support_case","support_attachment","organization","organization_document","distribution_declaration","distribution_payout_exception","distribution_tax_remittance"] as const;
const distributionHoldTargetTypes=["distribution_declaration","distribution_payout_exception","distribution_tax_remittance"] as const;
const holdChangeJson={type:"object",additionalProperties:false,required:["id","reference","targetType","targetId","changeType","reasonCategory","reason","status","requestedBy","reviewedBy","decisionReason","requestedAt","reviewedAt","appliedAt"],properties:{id:{type:"string",format:"uuid"},reference:{type:"string"},targetType:{type:"string",enum:holdTargetTypes},targetId:{type:"string",format:"uuid"},changeType:{type:"string",enum:["impose","release"]},reasonCategory:{type:"string",enum:["litigation","regulatory_request","audit","investigation","complaint","security_incident"]},reason:{type:"string"},status:{type:"string",enum:["pending","applied","rejected"]},requestedBy:actorJson,reviewedBy:{anyOf:[actorJson,{type:"null"}]},decisionReason:{anyOf:[{type:"string"},{type:"null"}]},requestedAt:{type:"string",format:"date-time"},reviewedAt:nullableDateJson,appliedAt:nullableDateJson}} as const;
const activeHoldJson={type:"object",additionalProperties:false,required:["id","reference","targetType","targetId","reasonCategory","reason","imposedBy","imposedAt","releasedAt"],properties:{id:{type:"string",format:"uuid"},reference:{type:"string"},targetType:{type:"string",enum:distributionHoldTargetTypes},targetId:{type:"string",format:"uuid"},reasonCategory:{type:"string"},reason:{type:"string"},imposedBy:actorJson,imposedAt:{type:"string",format:"date-time"},releasedAt:nullableDateJson}} as const;
const retentionPolicyJson={type:"object",additionalProperties:false,required:["versionId","reference","name","jurisdictionCode","legalBasisReference","recordClass","retentionDays","retentionStartedAt","retainUntil"],properties:{versionId:{type:"string",format:"uuid"},reference:{type:"string"},name:{type:"string"},jurisdictionCode:{type:"string"},legalBasisReference:{type:"string"},recordClass:{type:"string",enum:["distribution_declaration","payout_exception","tax_remittance"]},retentionDays:{type:"integer",minimum:1},retentionStartedAt:{type:"string",format:"date-time"},retainUntil:{type:"string",format:"date-time"}}} as const;
const distributionLifecycleJson={type:"object",additionalProperties:false,required:["targetType","targetId","retentionPolicy","privacyTreatments","activeHolds","pendingChanges"],properties:{targetType:{type:"string",enum:distributionHoldTargetTypes},targetId:{type:"string",format:"uuid"},retentionPolicy:{anyOf:[retentionPolicyJson,{type:"null"}]},privacyTreatments:{type:"array",items:{type:"object",additionalProperties:false,required:["reference","treatmentType","policyTreatmentMode","requesterVisibleSummary","executionResult","legalHoldActive","executedAt"],properties:{reference:{type:"string"},treatmentType:{type:"string",enum:["correction","erasure","restriction","objection"]},policyTreatmentMode:{type:"string"},requesterVisibleSummary:{type:"string"},executionResult:{type:"string"},legalHoldActive:{type:"boolean"},executedAt:{type:"string",format:"date-time"}}}},activeHolds:{type:"array",items:activeHoldJson},pendingChanges:{type:"array",items:holdChangeJson}}} as const;
const dispositionRequestJson={type:"object",additionalProperties:false,required:["id","reference","documentId","organizationId","action","reason","retainUntil","retentionPolicyVersionId","versionCount","status","requestedBy","reviewedBy","decisionReason","requestedAt","reviewedAt","appliedAt"],properties:{id:{type:"string",format:"uuid"},reference:{type:"string"},documentId:{type:"string",format:"uuid"},organizationId:{type:"string",format:"uuid"},action:{type:"string",enum:["delete_all_version_objects"]},reason:{type:"string"},retainUntil:{type:"string",format:"date-time"},retentionPolicyVersionId:{type:"string",format:"uuid"},versionCount:{type:"integer",minimum:1},status:{type:"string",enum:["pending","applied","rejected"]},requestedBy:actorJson,reviewedBy:{anyOf:[actorJson,{type:"null"}]},decisionReason:{anyOf:[{type:"string"},{type:"null"}]},requestedAt:{type:"string",format:"date-time"},reviewedAt:nullableDateJson,appliedAt:nullableDateJson}} as const;
const commandResponse=(request:typeof holdChangeJson|typeof dispositionRequestJson)=>({type:"object",additionalProperties:false,required:["request","replayed"],properties:{request,replayed:{type:"boolean"}}}) as const;

async function identity(request:FastifyRequest){requireRole(request.authUser,"admin");try{return await requirePostgresIdentityForSubject(request.authUser.userId);}catch(error){if(error instanceof PostgresIdentityUnavailableError)throw new HttpError(409,"Administrator identity is not available in PostgreSQL.");throw error;}}
function commandId(request:FastifyRequest){const value=readCommandId(request.headers);if(!value||value.length>200)throw new HttpError(400,"A valid X-Command-Id is required.");return value;}
function lifecycleError(error:unknown):never{if(error instanceof OrganizationDocumentLifecycleError||error instanceof SupportEvidenceLifecycleError)throw new HttpError(error.code==="not_found"?404:error.code==="forbidden"?403:error.code==="invalid_input"?400:409,error.message);throw error;}

export async function postgresAdminDataLifecycleRoutes(app:FastifyInstance){
  app.get("/v1/admin/distribution-lifecycle/:targetType/:targetId",{preHandler:[app.authenticate],schema:{tags:["Administration"],summary:"Read legal-hold state for a distribution record anchor",params:{type:"object",additionalProperties:false,required:["targetType","targetId"],properties:{targetType:{type:"string",enum:distributionHoldTargetTypes},targetId:{type:"string",format:"uuid"}}},response:{200:distributionLifecycleJson}}},async request=>{try{return await readDistributionLegalHoldLifecycle({actorIdentityId:await identity(request),...distributionTargetParams.parse(request.params)});}catch(error){lifecycleError(error);}});
  app.post("/v1/admin/distribution-lifecycle/:targetType/:targetId/legal-hold-requests",{preHandler:[app.authenticate],schema:{tags:["Administration"],summary:"Propose a distribution-record legal-hold change",headers:commandHeaders,params:{type:"object",additionalProperties:false,required:["targetType","targetId"],properties:{targetType:{type:"string",enum:distributionHoldTargetTypes},targetId:{type:"string",format:"uuid"}}},body:{type:"object",additionalProperties:false,required:["changeType","reasonCategory","reason"],properties:{changeType:{type:"string",enum:["impose","release"]},reasonCategory:{type:"string",enum:["litigation","regulatory_request","audit","investigation","complaint","security_incident"]},reason:{type:"string",minLength:20,maxLength:2000}}},response:{200:commandResponse(holdChangeJson)}}},async request=>{try{const target=distributionTargetParams.parse(request.params);return await proposeLegalHoldChange({actorIdentityId:await identity(request),...target,...distributionHoldBody.parse(request.body),commandKey:commandId(request)});}catch(error){lifecycleError(error);}});
  app.post("/v1/admin/distribution-lifecycle-hold-requests/:requestId/decision",{preHandler:[app.authenticate],schema:{tags:["Administration"],summary:"Independently decide a distribution-record legal-hold change",headers:commandHeaders,params:requestIdParams,body:{type:"object",additionalProperties:false,required:["decision","decisionReason"],properties:{decision:{type:"string",enum:["approve","reject"]},decisionReason:{type:"string",minLength:20,maxLength:2000}}},response:{200:commandResponse(holdChangeJson)}}},async request=>{try{return await decideLegalHoldChange({actorIdentityId:await identity(request),requestId:requestParams.parse(request.params).requestId,...decisionBody.parse(request.body)});}catch(error){lifecycleError(error);}});
  app.get("/v1/admin/organization-documents/lifecycle",{preHandler:[app.authenticate],schema:{tags:["Administration"],summary:"List organization documents for governed data lifecycle operations",querystring:{type:"object",additionalProperties:false,properties:{status:{type:"string",enum:["active","archived"]},limit:{type:"integer",minimum:1,maximum:200,default:100}}},response:{200:{type:"object",additionalProperties:false,required:["documents"],properties:{documents:{type:"array",items:documentSummaryJson}}}}}},async request=>{try{const query=listQuery.parse(request.query);return await listOrganizationDocumentsForLifecycle({actorIdentityId:await identity(request),...query});}catch(error){lifecycleError(error);}});
  app.get("/v1/admin/organization-documents/:documentId/lifecycle",{preHandler:[app.authenticate],schema:{tags:["Administration"],summary:"Read policy, hold, and disposition state for an organization document",params:idParams,response:{200:{type:"object",additionalProperties:false,required:["documentId","organizationId","title","status","retentionBindingStatus","retainUntil","retentionElapsed","versionCount","activeHolds","pendingHoldChanges","pendingDispositionRequest","disposition"],properties:{documentId:{type:"string",format:"uuid"},organizationId:{type:"string",format:"uuid"},title:{type:"string"},status:{type:"string",enum:["active","archived"]},retentionBindingStatus:{type:"string",enum:["legacy_declared","governed"]},retainUntil:{type:"string",format:"date-time"},retentionElapsed:{type:"boolean"},versionCount:{type:"integer",minimum:1},activeHolds:{type:"array",items:{type:"object",additionalProperties:false,required:["id","reference","targetType","targetId","reasonCategory","reason","imposedAt","imposedBy"],properties:{id:{type:"string",format:"uuid"},reference:{type:"string"},targetType:{type:"string",enum:["organization","organization_document"]},targetId:{type:"string",format:"uuid"},reasonCategory:{type:"string"},reason:{type:"string"},imposedAt:{type:"string",format:"date-time"},imposedBy:actorJson}}},pendingHoldChanges:{type:"array",items:{...holdChangeJson,required:["id","reference","targetType","targetId","changeType","reasonCategory","reason","status","requestedBy","requestedAt"]}},pendingDispositionRequest:{anyOf:[dispositionRequestJson,{type:"null"}]},disposition:{anyOf:[{type:"object",additionalProperties:false,required:["id","status","approvedAt","completedAt","failedAt"],properties:{id:{type:"string",format:"uuid"},status:{type:"string",enum:["cleanup_requested","completed","failed"]},approvedAt:{type:"string",format:"date-time"},completedAt:nullableDateJson,failedAt:nullableDateJson}},{type:"null"}]}}}}}},async request=>{try{return await readOrganizationDocumentLifecycle({actorIdentityId:await identity(request),documentId:documentParams.parse(request.params).documentId});}catch(error){lifecycleError(error);}});
  app.post("/v1/admin/organization-documents/:documentId/legal-hold-requests",{preHandler:[app.authenticate],schema:{tags:["Administration"],summary:"Propose an organization or document legal-hold change",headers:commandHeaders,params:idParams,body:{type:"object",additionalProperties:false,required:["scope","changeType","reasonCategory","reason"],properties:{scope:{type:"string",enum:["document","organization"]},changeType:{type:"string",enum:["impose","release"]},reasonCategory:{type:"string",enum:["litigation","regulatory_request","audit","investigation","complaint","security_incident"]},reason:{type:"string",minLength:20,maxLength:2000}}},response:{200:commandResponse(holdChangeJson)}}},async request=>{try{const actorIdentityId=await identity(request);const documentId=documentParams.parse(request.params).documentId;const lifecycle=await readOrganizationDocumentLifecycle({actorIdentityId,documentId});const body=holdBody.parse(request.body);return await proposeLegalHoldChange({actorIdentityId,targetType:body.scope==="document"?"organization_document":"organization",targetId:body.scope==="document"?documentId:lifecycle.organizationId,changeType:body.changeType,reasonCategory:body.reasonCategory,reason:body.reason,commandKey:commandId(request)});}catch(error){lifecycleError(error);}});
  app.post("/v1/admin/organization-document-hold-requests/:requestId/decision",{preHandler:[app.authenticate],schema:{tags:["Administration"],summary:"Independently decide an organization-document legal-hold change",headers:commandHeaders,params:requestIdParams,body:{type:"object",additionalProperties:false,required:["decision","decisionReason"],properties:{decision:{type:"string",enum:["approve","reject"]},decisionReason:{type:"string",minLength:20,maxLength:2000}}},response:{200:commandResponse(holdChangeJson)}}},async request=>{try{return await decideLegalHoldChange({actorIdentityId:await identity(request),requestId:requestParams.parse(request.params).requestId,...decisionBody.parse(request.body)});}catch(error){lifecycleError(error);}});
  app.post("/v1/admin/organization-documents/:documentId/disposition-requests",{preHandler:[app.authenticate],schema:{tags:["Administration"],summary:"Propose retention-gated deletion of every organization-document version object",headers:commandHeaders,params:idParams,body:{type:"object",additionalProperties:false,required:["reason"],properties:{reason:{type:"string",minLength:20,maxLength:2000}}},response:{200:commandResponse(dispositionRequestJson)}}},async request=>{try{return await proposeOrganizationDocumentDisposition({actorIdentityId:await identity(request),documentId:documentParams.parse(request.params).documentId,reason:dispositionBody.parse(request.body).reason,commandKey:commandId(request)});}catch(error){lifecycleError(error);}});
  app.post("/v1/admin/organization-document-disposition-requests/:requestId/decision",{preHandler:[app.authenticate],schema:{tags:["Administration"],summary:"Independently decide an organization-document disposition",headers:commandHeaders,params:requestIdParams,body:{type:"object",additionalProperties:false,required:["decision","decisionReason"],properties:{decision:{type:"string",enum:["approve","reject"]},decisionReason:{type:"string",minLength:20,maxLength:2000}}},response:{200:commandResponse(dispositionRequestJson)}}},async request=>{try{return await decideOrganizationDocumentDisposition({actorIdentityId:await identity(request),requestId:requestParams.parse(request.params).requestId,...decisionBody.parse(request.body)});}catch(error){lifecycleError(error);}});
}
