import { randomUUID } from "node:crypto";
import { env } from "../config/env.js";
import { requirePostgres, withPostgresTransaction } from "../db/postgres.js";
import { appendPostgresAuditEvent } from "../platform/postgres-audit.js";
import { appendOutboxEvent } from "../platform/postgres-outbox.js";
import { materializeAllocationChainOperations, releaseMintOperation } from "../platform/postgres-allocation-chain-operations.js";
import { assertTokenFactoryOwner, assertTokenFactorySupportsImmutableIssuanceCap, batchMint, waitForTransaction, whitelistInvestor } from "./blockchain.service.js";

export interface AllocationChainExecutorLogger { info: (obj: unknown, message?: string) => void; error: (obj: unknown, message?: string) => void; }
type Operation = { operationId: string; allocationId: string; organizationId: string; offeringId: string; chainId: number; tokenContractAddress: `0x${string}`; walletAddress: `0x${string}`; tokenAmount: string; operationType: "whitelist" | "mint"; claimId: string; transactionHash: `0x${string}` | null; };
type Submitted = Operation & { transactionHash: `0x${string}` };
const message = (error: unknown) => (error instanceof Error ? error.message : String(error)).slice(0, 2_000);

function assertTarget(operation: Operation) {
  if (operation.chainId !== env.CHAIN_ID) throw new Error(`Operation chain ${operation.chainId} does not match configured chain ${env.CHAIN_ID}`);
  if (BigInt(operation.tokenAmount) <= 0n) throw new Error("Allocation operation has an invalid token amount");
}
async function audit(client: Parameters<typeof appendPostgresAuditEvent>[0], operation: Operation, action: string, payload: Record<string, unknown>) {
  const event = await appendPostgresAuditEvent(client, { scopeKey: `organization:${operation.organizationId}`, organizationId: operation.organizationId, actorType: "system", action, entityType: "investment_allocation_chain_operation", entityId: operation.operationId, payload: { allocationRequestId: operation.allocationId, offeringId: operation.offeringId, operationType: operation.operationType, ...payload } });
  await appendOutboxEvent(client, { aggregateType: "investment_allocation_chain_operation", aggregateId: operation.operationId, eventType: action, payload: { organizationId: operation.organizationId, auditEventId: event.id } });
}
async function claim(workerId: string): Promise<Operation | null> {
  return withPostgresTransaction(async (client) => {
    const rows = await client.query<{ id: string; allocation_request_id: string; organization_id: string; offering_id: string; chain_id: number; token_contract_address: `0x${string}`; wallet_address: `0x${string}`; token_amount: string; operation_type: "whitelist" | "mint" }>(
      `SELECT operation.id, operation.allocation_request_id, operation.organization_id, operation.offering_id, operation.chain_id, operation.token_contract_address, operation.wallet_address, operation.token_amount, operation.operation_type
         FROM fractal.investment_allocation_chain_operations operation
        WHERE operation.status = 'approved' AND NOT EXISTS (SELECT 1 FROM fractal.investment_allocation_chain_dispatch_claims claim WHERE claim.operation_id = operation.id AND claim.status IN ('claimed','submitted','uncertain'))
        ORDER BY operation.created_at, operation.id FOR UPDATE OF operation SKIP LOCKED LIMIT 1`,
    );
    const row = rows.rows[0]; if (!row) return null;
    const claimId = randomUUID();
    await client.query("INSERT INTO fractal.investment_allocation_chain_dispatch_claims (id, operation_id, worker_id, status) VALUES ($1,$2,$3,'claimed')", [claimId, row.id, workerId]);
    return { operationId: row.id, allocationId: row.allocation_request_id, organizationId: row.organization_id, offeringId: row.offering_id, chainId: row.chain_id, tokenContractAddress: row.token_contract_address, walletAddress: row.wallet_address, tokenAmount: row.token_amount, operationType: row.operation_type, claimId, transactionHash: null };
  });
}
async function uncertain(operation: Operation, error: unknown) { const reason = message(error); await withPostgresTransaction(async (client) => { const updated = await client.query("UPDATE fractal.investment_allocation_chain_dispatch_claims SET status='uncertain', failure_reason=$2, completed_at=now() WHERE id=$1 AND status='claimed'", [operation.claimId, reason]); if (updated.rowCount !== 1) throw new Error("Allocation claim cannot be marked uncertain"); await audit(client, operation, "investment.allocation.chain_uncertain", { reason }); }); }
async function submitted(operation: Operation, transactionHash: `0x${string}`): Promise<Submitted> { return withPostgresTransaction(async (client) => { const op = await client.query("UPDATE fractal.investment_allocation_chain_operations SET status='submitted', transaction_hash=$2, submitted_at=now(), updated_at=now() WHERE id=$1 AND status='approved'", [operation.operationId, transactionHash.toLowerCase()]); if (op.rowCount !== 1) throw new Error("Allocation operation is no longer approved"); const claimUpdate = await client.query("UPDATE fractal.investment_allocation_chain_dispatch_claims SET status='submitted', transaction_hash=$2 WHERE id=$1 AND status='claimed'", [operation.claimId, transactionHash.toLowerCase()]); if (claimUpdate.rowCount !== 1) throw new Error("Allocation claim is no longer active"); const next = { ...operation, transactionHash }; await audit(client, next, "investment.allocation.chain_submitted", { transactionHash }); return next; }); }
async function confirmed(operation: Submitted, blockNumber: bigint) { await withPostgresTransaction(async (client) => { const op = await client.query("UPDATE fractal.investment_allocation_chain_operations SET status='confirmed', confirmed_at=now(), updated_at=now() WHERE id=$1 AND status='submitted' AND transaction_hash=$2", [operation.operationId, operation.transactionHash.toLowerCase()]); if (op.rowCount !== 1) throw new Error("Allocation operation cannot be confirmed"); const claimUpdate = await client.query("UPDATE fractal.investment_allocation_chain_dispatch_claims SET status='confirmed', completed_at=now() WHERE id=$1 AND status='submitted' AND transaction_hash=$2", [operation.claimId, operation.transactionHash.toLowerCase()]); if (claimUpdate.rowCount !== 1) throw new Error("Allocation dispatch claim cannot be confirmed"); await audit(client, operation, "investment.allocation.chain_confirmed", { transactionHash: operation.transactionHash, blockNumber: blockNumber.toString() }); }); if (operation.operationType === "whitelist") await releaseMintOperation({ whitelistOperationId: operation.operationId }); }
async function failed(operation: Submitted, error: unknown) { const reason = message(error); await withPostgresTransaction(async (client) => { await client.query("UPDATE fractal.investment_allocation_chain_operations SET status='failed', failure_reason=$2, updated_at=now() WHERE id=$1 AND status='submitted' AND transaction_hash=$3", [operation.operationId, reason, operation.transactionHash.toLowerCase()]); await client.query("UPDATE fractal.investment_allocation_chain_dispatch_claims SET status='failed', failure_reason=$2, completed_at=now() WHERE id=$1 AND status='submitted' AND transaction_hash=$3", [operation.claimId, reason, operation.transactionHash.toLowerCase()]); await audit(client, operation, "investment.allocation.chain_failed", { transactionHash: operation.transactionHash, reason }); }); }
async function reconcile(logger: AllocationChainExecutorLogger) { const rows = await requirePostgres().query<Operation & { transaction_hash: `0x${string}`; claim_id: string }>(`SELECT operation.id AS "operationId", operation.allocation_request_id AS "allocationId", operation.organization_id AS "organizationId", operation.offering_id AS "offeringId", operation.chain_id AS "chainId", operation.token_contract_address AS "tokenContractAddress", operation.wallet_address AS "walletAddress", operation.token_amount AS "tokenAmount", operation.operation_type AS "operationType", operation.transaction_hash, claim.id AS claim_id FROM fractal.investment_allocation_chain_operations operation JOIN LATERAL (SELECT id FROM fractal.investment_allocation_chain_dispatch_claims WHERE operation_id=operation.id AND status='submitted' ORDER BY claimed_at DESC LIMIT 1) claim ON true WHERE operation.status='submitted' ORDER BY operation.submitted_at, operation.id LIMIT $1`, [env.ALLOCATION_CHAIN_DISPATCH_BATCH_SIZE]); for (const row of rows.rows) { const operation: Submitted = { ...row, claimId: row.claim_id, transactionHash: row.transaction_hash }; try { assertTarget(operation); const receipt = await waitForTransaction(operation.transactionHash); if (receipt.status === "reverted") await failed(operation, new Error(`Transaction reverted: ${operation.transactionHash}`)); else { await confirmed(operation, receipt.blockNumber); logger.info({ operationId: operation.operationId, transactionHash: operation.transactionHash }, "Allocation chain operation confirmed"); } } catch (error) { logger.error({ err: error, operationId: operation.operationId }, "Allocation chain operation remains pending reconciliation"); } } }
async function dispatchOne(workerId: string, logger: AllocationChainExecutorLogger): Promise<boolean> { const operation = await claim(workerId); if (!operation) return false; let sent: Submitted | undefined; try { assertTarget(operation); await assertTokenFactoryOwner(); await assertTokenFactorySupportsImmutableIssuanceCap(); const transactionHash = operation.operationType === "whitelist" ? await whitelistInvestor(operation.tokenContractAddress, operation.walletAddress) : await batchMint(operation.tokenContractAddress, [{ wallet: operation.walletAddress, tokenAmount: BigInt(operation.tokenAmount), subscriptionId: operation.allocationId }]); sent = await submitted(operation, transactionHash); logger.info({ operationId: operation.operationId, transactionHash }, "Allocation chain operation submitted"); } catch (error) { if (!sent) await uncertain(operation, error).catch((markError) => logger.error({ err: markError, operationId: operation.operationId }, "Failed to record allocation uncertainty")); logger.error({ err: error, operationId: operation.operationId }, "Allocation chain operation was not broadcast or is uncertain"); } if (sent) await reconcile(logger); return true; }
export async function dispatchAllocationChainOperations(options: { workerId?: string; logger: AllocationChainExecutorLogger }): Promise<number> { if (!env.ALLOCATION_CHAIN_EXECUTOR_ENABLED) throw new Error("ALLOCATION_CHAIN_EXECUTOR_ENABLED must be true to dispatch allocation chain operations"); await materializeAllocationChainOperations(env.ALLOCATION_CHAIN_DISPATCH_BATCH_SIZE); await reconcile(options.logger); const workerId = options.workerId ?? randomUUID(); let count = 0; for (let index = 0; index < env.ALLOCATION_CHAIN_DISPATCH_BATCH_SIZE; index += 1) { if (!(await dispatchOne(workerId, options.logger))) break; count += 1; } return count; }
export function startAllocationChainExecutor(options: { logger: AllocationChainExecutorLogger; workerId?: string }) { const workerId = options.workerId ?? randomUUID(); let stopped = false; let running = false; const run = async () => { if (stopped || running) return; running = true; try { await dispatchAllocationChainOperations({ ...options, workerId }); } catch (error) { options.logger.error({ err: error }, "Allocation chain executor polling failed"); } finally { running = false; } }; const timer = setInterval(() => void run(), env.ALLOCATION_CHAIN_DISPATCH_INTERVAL_MS); timer.unref(); void run(); return { stop: () => { stopped = true; clearInterval(timer); } }; }
