import { beforeEach, describe, expect, it, vi } from "vitest";
const createQueue = vi.hoisted(() => vi.fn()); const find = vi.hoisted(() => vi.fn()); const findById = vi.hoisted(() => vi.fn()); const subscriptionById = vi.hoisted(() => vi.fn()); const receipt = vi.hoisted(() => vi.fn()); const updateMany = vi.hoisted(() => vi.fn()); const verify = vi.hoisted(() => vi.fn()); const transaction = vi.hoisted(() => vi.fn(async (fn) => fn({ id: "session" }))); const append = vi.hoisted(() => vi.fn());
vi.mock("../../../services/queue.js", () => ({ createQueue }));
vi.mock("../../../db/models.js", () => ({ PaymentIntentModel: { find, findById, updateMany }, SubscriptionModel: { findById: subscriptionById }, EscrowReceiptModel: { findOneAndUpdate: receipt }, LedgerEntryModel: {} }));
vi.mock("../../../services/paystack.js", () => ({ verifyPaystackTransaction: verify })); vi.mock("../../../utils/tx.js", () => ({ runInTransaction: transaction })); vi.mock("../../../utils/audit.js", () => ({ appendEvent: append }));
import { startPaymentVerificationQueue } from "../payment-verification.queue.js";
const log = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
beforeEach(() => { createQueue.mockReset(); find.mockReset(); findById.mockReset(); updateMany.mockReset(); verify.mockReset(); log.info.mockReset(); log.warn.mockReset(); });
describe("payment verification queue", () => {
  it("returns a safe handle when Redis is unavailable", async () => { createQueue.mockReturnValue(null); const h = startPaymentVerificationQueue(log); await h.triggerNow(); h.stop(); expect(log.warn).toHaveBeenCalledWith(expect.stringContaining("Redis not available")); });
  it("registers a queue, sweeps stale intents, and enqueues manual work", async () => { let handler: any; const add = vi.fn(); createQueue.mockImplementation((_n: string, h: any) => { handler = h; return { worker: { close: vi.fn().mockResolvedValue(undefined) }, queue: { close: vi.fn().mockResolvedValue(undefined), add } }; }); find.mockReturnValue({ limit: vi.fn().mockResolvedValue([{ _id: "intent", paystackReference: "ref" }, { _id: "skip" }]) }); verify.mockResolvedValue({ status: "failed" }); updateMany.mockResolvedValue({ modifiedCount: 2 }); const h = startPaymentVerificationQueue(log); await handler(); await h.triggerNow(); h.stop(); expect(add).toHaveBeenCalledWith("manual-trigger", {}, { priority: 1 }); expect(log.info).toHaveBeenCalledWith({ verified: 0, expired: 2 }, "Queue sweep completed"); });
  it("records a matched payment once inside a transaction", async () => { let handler: any; createQueue.mockImplementation((_n: string, h: any) => { handler = h; return { worker: { close: vi.fn() }, queue: { close: vi.fn(), add: vi.fn() } }; }); find.mockReturnValue({ limit: vi.fn().mockResolvedValue([{ _id: "intent", paystackReference: "ref" }]) }); verify.mockResolvedValue({ status: "success", amount: 5000, currency: "NGN", paid_at: "2026-01-01T00:00:00.000Z" }); const intent = { _id: "intent", status: "pending", subscriptionId: "subscription", save: vi.fn() }; findById.mockReturnValue({ session: vi.fn().mockResolvedValue(intent) }); const subscription = { _id: "subscription", investorUserId: "investor", status: "pending", save: vi.fn() }; subscriptionById.mockReturnValue({ session: vi.fn().mockResolvedValue(subscription) }); receipt.mockResolvedValue({}); updateMany.mockResolvedValue({ modifiedCount: 0 }); await startPaymentVerificationQueue(log).triggerNow(); await handler(); expect(intent.status).toBe("amount_matched"); expect(subscription.status).toBe("paid"); expect(append).toHaveBeenCalled(); });
});
