import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import { requireFreshTotpStepUp, StepUpRequiredError } from "../../../platform/auth-step-up.js";
import { PostgresIdentityUnavailableError, requirePostgresIdentityForSubject } from "../../../platform/postgres-identities.js";
import { acknowledgeInvestorOfferingNotice, decideOfferingNotice, getOfferingNoticePolicyOptions, getOfferingNoticeRequest, listInvestorOfferingNotices, listOfferingNoticeRequests, markInvestorOfferingNoticeRead, OfferingNoticeError, offeringNoticeCategories, submitOfferingNotice } from "../../../platform/postgres-offering-notices.js";
import { requireOrganizationAccess, TenantAccessError } from "../../../platform/tenant-access.js";
import { HttpError } from "../../../utils/errors.js";
import { readCommandId } from "../../../utils/idempotency.js";
import { authorize } from "../../../utils/rbac.js";

const uuid=z.string().uuid();
const orgParams=z.object({organizationId:uuid});const requestParams=z.object({requestId:uuid});const noticeParams=z.object({noticeId:uuid});
const submitBody=z.object({offeringId:uuid,category:z.enum(offeringNoticeCategories),subject:z.string().trim().min(5).max(240),body:z.string().trim().min(20).max(12000)});
const decisionBody=z.object({decision:z.enum(["approve","reject"]),decisionReason:z.string().trim().min(20).max(2000)});
const commandHeaders={type:"object",required:["x-command-id"],properties:{"x-command-id":{type:"string",minLength:1,maxLength:200}}} as const;
const idParams=(key:string)=>({type:"object",additionalProperties:false,required:[key],properties:{[key]:{type:"string",format:"uuid"}}}) as const;
const errorResponses={400:{type:"object"},401:{type:"object"},403:{type:"object"},409:{type:"object"},422:{type:"object"}} as const;
const nullableString={anyOf:[{type:"string"},{type:"null"}]} as const;const nullableDate={anyOf:[{type:"string",format:"date-time"},{type:"null"}]} as const;const nullableUuid={anyOf:[{type:"string",format:"uuid"},{type:"null"}]} as const;const nullableInteger={anyOf:[{type:"integer",minimum:0},{type:"null"}]} as const;
const actorJson={type:"object",additionalProperties:false,required:["id","legalName"],properties:{id:{type:"string",format:"uuid"},legalName:{type:"string"}}} as const;
const policyJson={type:"object",additionalProperties:false,required:["versionId","reference","name","jurisdictionCode","legalBasisReference","retentionDays"],properties:{versionId:{type:"string",format:"uuid"},reference:{type:"string"},name:{type:"string"},jurisdictionCode:{type:"string",pattern:"^[A-Z]{2}$"},legalBasisReference:{type:"string"},retentionDays:{type:"integer",minimum:1,maximum:9131}}} as const;
const acknowledgmentJson={type:"object",additionalProperties:false,required:["required","windowDays","dueAt"],properties:{required:{type:"boolean"},windowDays:nullableInteger,dueAt:nullableDate}} as const;
const requestJson={type:"object",additionalProperties:false,required:["id","reference","organizationId","offeringId","publicReference","offeringName","category","subject","body","status","policy","acknowledgment","submittedBy","submittedAt","reviewedBy","reviewedAt","decisionReason","publishedNoticeId","audienceCount","retainUntil","readCount","acknowledgedCount"],properties:{id:{type:"string",format:"uuid"},reference:{type:"string"},organizationId:{type:"string",format:"uuid"},offeringId:{type:"string",format:"uuid"},publicReference:{type:"string"},offeringName:{type:"string"},category:{type:"string",enum:offeringNoticeCategories},subject:{type:"string"},body:{type:"string"},status:{type:"string",enum:["submitted","approved","rejected"]},policy:policyJson,acknowledgment:acknowledgmentJson,submittedBy:actorJson,submittedAt:{type:"string",format:"date-time"},reviewedBy:{anyOf:[actorJson,{type:"null"}]},reviewedAt:nullableDate,decisionReason:nullableString,publishedNoticeId:nullableUuid,audienceCount:nullableInteger,retainUntil:nullableDate,readCount:{type:"integer",minimum:0},acknowledgedCount:{type:"integer",minimum:0}}} as const;
const policyOptionsJson={type:"object",additionalProperties:false,required:["policy","rules"],properties:{policy:{type:"object",additionalProperties:false,required:["versionId","versionNumber","reference","name","schemaVersion","jurisdictionCode","legalBasisReference"],properties:{versionId:{type:"string",format:"uuid"},versionNumber:{type:"integer",minimum:1},reference:{type:"string"},name:{type:"string"},schemaVersion:{type:"string",enum:["offering-notice-policy-v1"]},jurisdictionCode:{type:"string",pattern:"^[A-Z]{2}$"},legalBasisReference:{type:"string"}}},rules:{type:"array",minItems:5,maxItems:5,items:{type:"object",additionalProperties:false,required:["category","retentionDays","acknowledgmentRequired","acknowledgmentWindowDays"],properties:{category:{type:"string",enum:offeringNoticeCategories},retentionDays:{type:"integer",minimum:1,maximum:9131},acknowledgmentRequired:{type:"boolean"},acknowledgmentWindowDays:nullableInteger}}}}} as const;
const recipientCommandJson={type:"object",additionalProperties:false,required:["noticeId","replayed","occurredAt"],properties:{noticeId:{type:"string",format:"uuid"},replayed:{type:"boolean"},occurredAt:{type:"string",format:"date-time"}}} as const;
const noticeJson={type:"object",additionalProperties:false,required:["id","organizationName","publicReference","offeringName","category","subject","body","policyReference","legalBasisReference","retainUntil","acknowledgmentRequired","acknowledgmentDueAt","publishedAt","firstReadAt","acknowledgedAt"],properties:{id:{type:"string",format:"uuid"},organizationName:{type:"string"},publicReference:{type:"string"},offeringName:{type:"string"},category:{type:"string",enum:offeringNoticeCategories},subject:{type:"string"},body:{type:"string"},policyReference:{type:"string"},legalBasisReference:{type:"string"},retainUntil:{type:"string",format:"date-time"},acknowledgmentRequired:{type:"boolean"},acknowledgmentDueAt:{anyOf:[{type:"string",format:"date-time"},{type:"null"}]},publishedAt:{type:"string",format:"date-time"},firstReadAt:{anyOf:[{type:"string",format:"date-time"},{type:"null"}]},acknowledgedAt:{anyOf:[{type:"string",format:"date-time"},{type:"null"}]}}} as const;

async function identity(request:FastifyRequest){try{return await requirePostgresIdentityForSubject(request.authUser.userId);}catch(error){if(error instanceof PostgresIdentityUnavailableError)throw new HttpError(409,"Your account migration is not ready for governed notices.");throw error;}}
function actor(request:FastifyRequest,role:"issuer"|"investor"){if(request.authUser.role!==role)throw new HttpError(403,`${role==="issuer"?"Issuer":"Investor"} role required.`);}
async function scope(identityId:string,organizationId:string,roles:readonly("owner"|"administrator"|"offering_manager"|"compliance_reviewer"|"viewer")[]){try{await requireOrganizationAccess({identityId,organizationId,allowedRoles:roles});}catch(error){if(error instanceof TenantAccessError)throw new HttpError(403,"You do not have the required organization role.");throw error;}}
async function stepUp(request:FastifyRequest,identityId:string){try{await requireFreshTotpStepUp({sessionId:request.authUser.sessionId,identityId});}catch(error){if(error instanceof StepUpRequiredError)throw new HttpError(403,error.message);throw error;}}
function governed<T>(operation:()=>Promise<T>){return operation().catch(error=>{if(error instanceof OfferingNoticeError)throw new HttpError(error.code==="not_found"?404:error.code==="forbidden"?403:error.code==="invalid_input"?422:409,error.message);throw error;});}
function commandId(request:FastifyRequest){const value=readCommandId(request.headers);if(!value)throw new HttpError(400,"X-Command-ID header is required.");return value;}

export async function postgresOfferingNoticeRoutes(app:FastifyInstance){
  app.get("/v1/governance/organizations/:organizationId/offering-notice-policy",{preHandler:[app.authenticate],schema:{params:idParams("organizationId"),response:{200:policyOptionsJson,...errorResponses}}},async request=>{actor(request,"issuer");authorize(request.authUser,"read","offering");const {organizationId}=orgParams.parse(request.params),identityId=await identity(request);await scope(identityId,organizationId,["owner","administrator","offering_manager","compliance_reviewer","viewer"]);return governed(()=>getOfferingNoticePolicyOptions(organizationId));});
  app.get("/v1/governance/organizations/:organizationId/offering-notice-requests",{preHandler:[app.authenticate],schema:{params:idParams("organizationId"),response:{200:{type:"object",additionalProperties:false,required:["requests"],properties:{requests:{type:"array",items:requestJson}}},...errorResponses}}},async request=>{actor(request,"issuer");authorize(request.authUser,"read","offering");const {organizationId}=orgParams.parse(request.params),identityId=await identity(request);await scope(identityId,organizationId,["owner","administrator","offering_manager","compliance_reviewer","viewer"]);return{requests:await listOfferingNoticeRequests(organizationId)};});
  app.post("/v1/governance/organizations/:organizationId/offering-notice-requests",{preHandler:[app.authenticate],schema:{params:idParams("organizationId"),headers:commandHeaders,body:{type:"object",additionalProperties:false,required:["offeringId","category","subject","body"],properties:{offeringId:{type:"string",format:"uuid"},category:{type:"string",enum:offeringNoticeCategories},subject:{type:"string",minLength:5,maxLength:240},body:{type:"string",minLength:20,maxLength:12000}}},response:{200:{type:"object",additionalProperties:false,required:["requestId","replayed"],properties:{requestId:{type:"string",format:"uuid"},replayed:{type:"boolean"}}},...errorResponses}}},async request=>{actor(request,"issuer");authorize(request.authUser,"submit","offering");const {organizationId}=orgParams.parse(request.params),identityId=await identity(request);await scope(identityId,organizationId,["owner","administrator","offering_manager"]);return governed(()=>submitOfferingNotice({organizationId,actorIdentityId:identityId,commandKey:commandId(request),...submitBody.parse(request.body)}));});
  app.post("/v1/governance/offering-notice-requests/:requestId/decision",{preHandler:[app.authenticate],schema:{params:idParams("requestId"),body:{type:"object",additionalProperties:false,required:["decision","decisionReason"],properties:{decision:{type:"string",enum:["approve","reject"]},decisionReason:{type:"string",minLength:20,maxLength:2000}}},response:{200:{type:"object",additionalProperties:false,required:["requestId","status","publishedNoticeId","replayed"],properties:{requestId:{type:"string",format:"uuid"},status:{type:"string",enum:["approved","rejected"]},publishedNoticeId:{anyOf:[{type:"string",format:"uuid"},{type:"null"}]},replayed:{type:"boolean"}}},...errorResponses}}},async request=>{actor(request,"issuer");authorize(request.authUser,"approve","offering");const {requestId}=requestParams.parse(request.params),record=await getOfferingNoticeRequest(requestId);if(!record)throw new HttpError(404,"Offering notice request not found.");const identityId=await identity(request);await scope(identityId,record.organizationId,["owner","administrator","compliance_reviewer"]);await stepUp(request,identityId);return governed(()=>decideOfferingNotice({requestId,actorIdentityId:identityId,...decisionBody.parse(request.body)}));});
  app.get("/v1/investor/notices",{preHandler:[app.authenticate],schema:{response:{200:{type:"object",additionalProperties:false,required:["notices"],properties:{notices:{type:"array",items:noticeJson}}},...errorResponses}}},async request=>{actor(request,"investor");authorize(request.authUser,"read","investor_profile");return{notices:await listInvestorOfferingNotices(await identity(request))};});
  app.post("/v1/investor/notices/:noticeId/read",{preHandler:[app.authenticate],schema:{params:idParams("noticeId"),response:{200:recipientCommandJson,...errorResponses}}},async request=>{actor(request,"investor");authorize(request.authUser,"read","investor_profile");const identityId=await identity(request);return governed(()=>markInvestorOfferingNoticeRead(identityId,noticeParams.parse(request.params).noticeId));});
  app.post("/v1/investor/notices/:noticeId/acknowledge",{preHandler:[app.authenticate],schema:{params:idParams("noticeId"),response:{200:recipientCommandJson,...errorResponses}}},async request=>{actor(request,"investor");authorize(request.authUser,"update","investor_profile");const identityId=await identity(request);return governed(()=>acknowledgeInvestorOfferingNotice(identityId,noticeParams.parse(request.params).noticeId));});
}
