import { beforeEach, describe, expect, it, vi } from "vitest";
const m=vi.hoisted(()=>({tx:vi.fn(),pg:vi.fn(),audit:vi.fn(),outbox:vi.fn()}));
vi.mock("../../db/postgres.js",()=>({withPostgresTransaction:m.tx,requirePostgres:m.pg}));vi.mock("../postgres-audit.js",()=>({appendPostgresAuditEvent:m.audit}));vi.mock("../postgres-outbox.js",()=>({appendOutboxEvent:m.outbox}));
import { decideOfferingChainDeploymentRequest, getOfferingChainDeploymentRequest, listOfferingChainDeploymentRequests, listOfferingChainOperations, submitOfferingChainDeploymentRequest } from "../postgres-offering-chain-deployments.js";
function c(...xs:any[]){const query=vi.fn();xs.forEach(x=>query.mockResolvedValueOnce({rows:[],rowCount:0,...x}));return{query};}
const addr="0x1111111111111111111111111111111111111111";
const request={id:"request-1",organization_id:"org-1",offering_id:"offering-1",offering_version_id:"version-1",issuance_terms_request_id:"terms-1",chain_id:1,token_factory_address:addr,offering_name:"Offering",token_name:"Offering Token",token_symbol:"OFT",max_balance_per_holder:"0",retail_cap:"0",max_total_supply:"1000",status:"submitted",submitted_by_identity_id:"maker",submitted_at:new Date(),decided_by_identity_id:null,decided_at:null,decision_reason:null};
beforeEach(()=>{vi.clearAllMocks();m.tx.mockImplementation(async(w:any)=>w({query:vi.fn()}));m.pg.mockReturnValue({query:vi.fn()});m.audit.mockResolvedValue({id:"audit"});m.outbox.mockResolvedValue(undefined);});
describe("offering chain deployments",()=>{
 it("captures only approved terms for a published offering",async()=>{const x=c({rows:[{id:"offering-1",current_version_id:"version-1"}]},{rows:[{max_total_supply:"1000",status:"approved",organization_id:"org-1",offering_id:"offering-1",offering_version_id:"version-1"}]},{ });m.tx.mockImplementation(async(w:any)=>w(x));await expect(submitOfferingChainDeploymentRequest({organizationId:"org-1",offeringId:"offering-1",issuanceTermsRequestId:"terms-1",submittedByIdentityId:"maker",chainId:1,tokenFactoryAddress:addr,offeringName:"Offering",tokenName:"Offering Token",tokenSymbol:"oft"})).resolves.toMatchObject({requestId:expect.any(String)});expect(m.outbox).toHaveBeenCalled();});
 it("rejects invalid deployment input or non-current terms",async()=>{await expect(submitOfferingChainDeploymentRequest({organizationId:"org",offeringId:"offer",issuanceTermsRequestId:"terms",submittedByIdentityId:"maker",chainId:0,tokenFactoryAddress:"bad",offeringName:"",tokenName:"",tokenSymbol:"x"})).rejects.toThrow("chainId");const x=c({rows:[]});m.tx.mockImplementation(async(w:any)=>w(x));await expect(submitOfferingChainDeploymentRequest({organizationId:"org-1",offeringId:"offering-1",issuanceTermsRequestId:"terms-1",submittedByIdentityId:"maker",chainId:1,tokenFactoryAddress:addr,offeringName:"Offering",tokenName:"Token",tokenSymbol:"TK"})).rejects.toThrow("published offering");});
 it("rejects negative limits and terms that do not match the current offering version",async()=>{await expect(submitOfferingChainDeploymentRequest({organizationId:"org-1",offeringId:"offering-1",issuanceTermsRequestId:"terms-1",submittedByIdentityId:"maker",chainId:1,tokenFactoryAddress:addr,offeringName:"Offering",tokenName:"Token",tokenSymbol:"TK",retailCap:-1})).rejects.toThrow("retailCap");const x=c({rows:[{id:"offering-1",current_version_id:"version-1"}]},{rows:[{max_total_supply:"1000",status:"approved",organization_id:"org-1",offering_id:"offering-1",offering_version_id:"old-version"}]});m.tx.mockImplementation(async(w:any)=>w(x));await expect(submitOfferingChainDeploymentRequest({organizationId:"org-1",offeringId:"offering-1",issuanceTermsRequestId:"terms-1",submittedByIdentityId:"maker",chainId:1,tokenFactoryAddress:addr,offeringName:"Offering",tokenName:"Token",tokenSymbol:"TK",retailCap:10})).rejects.toThrow("approved issuance terms");});
 it("requires independent approval and creates an operation",async()=>{const self=c({rows:[request]});m.tx.mockImplementation(async(w:any)=>w(self));await expect(decideOfferingChainDeploymentRequest({requestId:"request-1",decidedByIdentityId:"maker",approve:true})).rejects.toThrow("different person");const x=c({rows:[request]},{},{},{});m.tx.mockImplementation(async(w:any)=>w(x));await expect(decideOfferingChainDeploymentRequest({requestId:"request-1",decidedByIdentityId:"checker",approve:true})).resolves.toMatchObject({status:"approved",operationId:expect.any(String)});});
 it("maps request and operation lists",async()=>{const op={id:"operation-1",request_id:"request-1",organization_id:"org-1",offering_id:"offering-1",chain_id:1,token_factory_address:addr,operation_type:"deploy_token",status:"confirmed",transaction_hash:"0xabc",token_contract_address:addr,block_number:"1",submitted_at:new Date(),confirmed_at:new Date(),failure_reason:null,created_at:new Date(),updated_at:new Date()};const query=vi.fn().mockResolvedValueOnce({rows:[request]}).mockResolvedValueOnce({rows:[request]}).mockResolvedValueOnce({rows:[op]});m.pg.mockReturnValue({query});await expect(getOfferingChainDeploymentRequest("request-1")).resolves.toMatchObject({id:"request-1",chainId:1});await expect(listOfferingChainDeploymentRequests({organizationId:"org-1"})).resolves.toHaveLength(1);await expect(listOfferingChainOperations({organizationId:"org-1"})).resolves.toHaveLength(1);});
});
