import { beforeEach, describe, expect, it, vi } from "vitest";
const tx=vi.hoisted(()=>vi.fn());vi.mock("../../db/postgres.js",()=>({withPostgresTransaction:tx}));
import { JournalIdempotencyConflictError, JournalValidationError, ensureLedgerAccount, postJournal, postJournalInTransaction, reverseJournal } from "../postgres-journal.js";
function c(...xs:any[]){const query=vi.fn();xs.forEach(x=>query.mockResolvedValueOnce({rows:[],rowCount:0,...x}));return{query};}
const input={scopeKey:"org:1",organizationId:"org-1",idempotencyKey:"key-1",currency:"usd",narrative:"Payment",postings:[{accountCode:"ASSET.CASH",direction:"debit" as const,amountMinor:100},{accountCode:"LIABILITY.ESCROW",direction:"credit" as const,amountMinor:100}]};
beforeEach(()=>{vi.clearAllMocks();tx.mockImplementation(async(w:any)=>w({query:vi.fn()}));});
describe("journal authority",()=>{
 it("creates immutable accounts and rejects invalid account input",async()=>{const x=c({rows:[{id:"account-1"}],rowCount:1});await expect(ensureLedgerAccount(x as any,{code:"asset.cash",name:"Cash",accountType:"asset",normalBalance:"debit"})).resolves.toBe("account-1");expect(x.query.mock.calls[0]?.[1]).toEqual(expect.arrayContaining(["ASSET.CASH"]));await expect(ensureLedgerAccount(x as any,{code:"?",name:"",accountType:"asset",normalBalance:"debit"})).rejects.toBeInstanceOf(JournalValidationError);});
 it("posts balanced journals and resolves all active accounts",async()=>{const x=c({rows:[{id:"journal-1"}],rowCount:1},{rows:[{id:"a",code:"ASSET.CASH"},{id:"b",code:"LIABILITY.ESCROW"}],rowCount:2},{},{});await expect(postJournalInTransaction(x as any,input)).resolves.toMatchObject({journalId:expect.any(String),replayed:false});expect(x.query).toHaveBeenCalledTimes(4);});
 it("rejects invalid, unbalanced, and unknown-account postings",async()=>{await expect(postJournalInTransaction({query:vi.fn()} as any,{...input,currency:"US"})).rejects.toThrow("ISO");await expect(postJournalInTransaction({query:vi.fn()} as any,{...input,postings:[input.postings[0],{...input.postings[1],amountMinor:99}]})).rejects.toThrow("equal");const x=c({rows:[{id:"journal"}],rowCount:1},{rows:[{id:"a",code:"ASSET.CASH"}],rowCount:1});await expect(postJournalInTransaction(x as any,input)).rejects.toThrow("Unknown");});
 it("rejects invalid directions and amounts before it writes a journal",async()=>{await expect(postJournalInTransaction({query:vi.fn()} as any,{...input,postings:[{...input.postings[0],direction:"other" as any},input.postings[1]]})).rejects.toThrow("direction");await expect(postJournalInTransaction({query:vi.fn()} as any,{...input,postings:[{...input.postings[0],amountMinor:0},input.postings[1]]})).rejects.toThrow("positive safe");await expect(postJournalInTransaction({query:vi.fn()} as any,{...input,postings:[{...input.postings[0],amountMinor:9223372036854775808n},{...input.postings[1],amountMinor:9223372036854775808n}]})).rejects.toThrow("BIGINT");});
 it("returns exact idempotent replays and rejects changed payloads",async()=>{const first=c({rows:[],rowCount:0},{rows:[{id:"journal-old",request_hash:"different"}],rowCount:1});await expect(postJournalInTransaction(first as any,input)).rejects.toBeInstanceOf(JournalIdempotencyConflictError);const hashClient=c({rows:[{id:"journal"}],rowCount:1},{rows:[{id:"a",code:"ASSET.CASH"},{id:"b",code:"LIABILITY.ESCROW"}],rowCount:2},{},{});await postJournalInTransaction(hashClient as any,input);const requestHash=hashClient.query.mock.calls[0]?.[1]?.[4];const replay=c({rows:[],rowCount:0},{rows:[{id:"journal-old",request_hash:requestHash}],rowCount:1});await expect(postJournalInTransaction(replay as any,input)).resolves.toEqual({journalId:"journal-old",replayed:true});});
 it("posts and reverses through transaction wrappers",async()=>{const x=c({rows:[{id:"journal"}],rowCount:1},{rows:[{id:"a",code:"ASSET.CASH"},{id:"b",code:"LIABILITY.ESCROW"}],rowCount:2},{},{});tx.mockImplementation(async(w:any)=>w(x));await expect(postJournal(input)).resolves.toMatchObject({replayed:false});const r=c({rows:[{currency:"USD"}],rowCount:1},{rows:[{code:"ASSET.CASH",direction:"debit",amount_minor:"100",metadata:{}},{code:"LIABILITY.ESCROW",direction:"credit",amount_minor:"100",metadata:{}}],rowCount:2},{rows:[{id:"reverse"}],rowCount:1},{rows:[{id:"a",code:"ASSET.CASH"},{id:"b",code:"LIABILITY.ESCROW"}],rowCount:2},{},{});tx.mockImplementation(async(w:any)=>w(r));await expect(reverseJournal({scopeKey:"org:1",organizationId:"org-1",idempotencyKey:"rev-1",narrative:"",originalJournalId:"original"})).resolves.toMatchObject({replayed:false});});
});
