import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import { PostgresIdentityUnavailableError, requirePostgresIdentityForSubject } from "../../../platform/postgres-identities.js";
import { decideDistributionDeclaration, decideOwnershipSnapshot, DistributionAuthorityError, getDistributionDeclaration, getDistributionPolicyOptions, getOwnershipSnapshotRequest, listDistributionDeclarations, listInvestorDistributionEntitlements, listOwnershipSnapshotRequests, submitDistributionDeclaration, submitOwnershipSnapshot } from "../../../platform/postgres-distributions.js";
import { requireOrganizationAccess, TenantAccessError } from "../../../platform/tenant-access.js";
import { HttpError } from "../../../utils/errors.js";
import { readCommandId } from "../../../utils/idempotency.js";
import { authorize } from "../../../utils/rbac.js";

const uuid=z.string().uuid(),orgParams=z.object({organizationId:uuid}),requestParams=z.object({requestId:uuid});
const snapshotBody=z.object({offeringId:uuid,chainId:z.number().int().positive(),tokenContractAddress:z.string().regex(/^0x[a-fA-F0-9]{40}$/),recordAt:z.coerce.date(),blockNumber:z.string().regex(/^[0-9]{1,19}$/),blockHash:z.string().regex(/^0x[a-fA-F0-9]{64}$/),confirmations:z.number().int().nonnegative(),sourceType:z.enum(["independent_indexer","archive_rpc"]),sourceReference:z.string().trim().min(3).max(300),sourceManifestSha256:z.string().regex(/^[a-fA-F0-9]{64}$/),totalSupplyUnits:z.string().regex(/^[1-9][0-9]{0,77}$/),holdings:z.array(z.object({walletAddress:z.string().regex(/^0x[a-fA-F0-9]{40}$/),balanceUnits:z.string().regex(/^[1-9][0-9]{0,77}$/),sourceRowSha256:z.string().regex(/^[a-fA-F0-9]{64}$/)}).strict()).min(1).max(10_000)}).strict();
const declarationBody=z.object({offeringId:uuid,ownershipSnapshotRequestId:uuid,periodLabel:z.string().trim().min(3).max(120),currency:z.string().regex(/^[A-Za-z]{3}$/),grossAmountMinor:z.string().regex(/^[1-9][0-9]{0,18}$/),withholdingTaxBps:z.number().int().min(0).max(10_000),paymentDueAt:z.coerce.date()}).strict();
const decisionBody=z.object({decision:z.enum(["approve","reject"]),decisionReason:z.string().trim().min(20).max(2000)}).strict(),currencyQuery=z.object({currency:z.string().regex(/^[A-Za-z]{3}$/)});
const idParams=(key:string)=>({type:"object",additionalProperties:false,required:[key],properties:{[key]:{type:"string",format:"uuid"}}}) as const;
const commandHeaders={type:"object",required:["x-command-id"],properties:{"x-command-id":{type:"string",minLength:1,maxLength:200}}} as const;
const errors={400:{type:"object"},401:{type:"object"},403:{type:"object"},404:{type:"object"},409:{type:"object"},422:{type:"object"}} as const;
const text={type:"string"} as const,uuidJson={type:"string",format:"uuid"} as const,dateJson={type:"string",format:"date-time"} as const,integerText={type:"string",pattern:"^[0-9]+$"} as const;
const nullable=(value:object)=>({anyOf:[value,{type:"null"}]}) as const;
const actorJson={type:"object",additionalProperties:false,required:["id","legalName"],properties:{id:uuidJson,legalName:text}} as const;
const snapshotJson={type:"object",additionalProperties:false,required:["id","reference","organizationId","offeringId","publicReference","offeringName","chainId","tokenContractAddress","recordAt","blockNumber","blockHash","confirmations","sourceType","sourceReference","sourceManifestSha256","totalSupplyUnits","holderCount","status","submittedBy","submittedAt","reviewedBy","reviewedAt","decisionReason"],properties:{id:uuidJson,reference:text,organizationId:uuidJson,offeringId:uuidJson,publicReference:text,offeringName:text,chainId:{type:"integer",minimum:1},tokenContractAddress:text,recordAt:dateJson,blockNumber:integerText,blockHash:text,confirmations:{type:"integer",minimum:0},sourceType:{type:"string",enum:["independent_indexer","archive_rpc"]},sourceReference:text,sourceManifestSha256:text,totalSupplyUnits:integerText,holderCount:{type:"integer",minimum:1},status:{type:"string",enum:["submitted","approved","rejected"]},submittedBy:actorJson,submittedAt:dateJson,reviewedBy:nullable(actorJson),reviewedAt:nullable(dateJson),decisionReason:nullable(text)}} as const;
const policyJson={type:"object",additionalProperties:false,required:["versionId","reference","name","jurisdictionCode","legalBasisReference","retentionDays"],properties:{versionId:uuidJson,reference:text,name:text,jurisdictionCode:text,legalBasisReference:text,retentionDays:{type:"integer",minimum:1}}} as const;
const declarationJson={type:"object",additionalProperties:false,required:["id","reference","organizationId","offeringId","publicReference","offeringName","ownershipSnapshotRequestId","periodLabel","currency","grossAmountMinor","withholdingTaxBps","withholdingTaxMinor","netAmountMinor","paymentDueAt","entitlementCount","status","policy","retainUntil","submittedBy","submittedAt","reviewedBy","reviewedAt","decisionReason","declarationJournalId","payoutStatus"],properties:{id:uuidJson,reference:text,organizationId:uuidJson,offeringId:uuidJson,publicReference:text,offeringName:text,ownershipSnapshotRequestId:uuidJson,periodLabel:text,currency:text,grossAmountMinor:integerText,withholdingTaxBps:{type:"integer"},withholdingTaxMinor:integerText,netAmountMinor:integerText,paymentDueAt:dateJson,entitlementCount:{type:"integer",minimum:1},status:{type:"string",enum:["submitted","approved","rejected"]},policy:policyJson,retainUntil:dateJson,submittedBy:actorJson,submittedAt:dateJson,reviewedBy:nullable(actorJson),reviewedAt:nullable(dateJson),decisionReason:nullable(text),declarationJournalId:nullable(uuidJson),payoutStatus:{type:"string",enum:["not_instructed"]}}} as const;
const entitlementJson={type:"object",additionalProperties:false,required:["id","reference","organizationName","publicReference","offeringName","periodLabel","currency","balanceUnits","grossAmountMinor","withholdingTaxMinor","netAmountMinor","paymentDueAt","declaredAt","retainUntil","policyReference","legalBasisReference","declarationJournalId","payoutStatus","payoutReference","payoutSubmittedAt","payoutConfirmedAt","payoutFailedAt","payoutFailureReason","settlementJournalId","reversalJournalId"],properties:{id:uuidJson,reference:text,organizationName:text,publicReference:text,offeringName:text,periodLabel:text,currency:text,balanceUnits:integerText,grossAmountMinor:integerText,withholdingTaxMinor:integerText,netAmountMinor:integerText,paymentDueAt:dateJson,declaredAt:dateJson,retainUntil:dateJson,policyReference:text,legalBasisReference:text,declarationJournalId:uuidJson,payoutStatus:{type:"string",enum:["not_instructed","authorized","dispatching","submitted","uncertain","confirmed","failed","reversed"]},payoutReference:nullable(text),payoutSubmittedAt:nullable(dateJson),payoutConfirmedAt:nullable(dateJson),payoutFailedAt:nullable(dateJson),payoutFailureReason:nullable(text),settlementJournalId:nullable(uuidJson),reversalJournalId:nullable(uuidJson)}} as const;
const snapshotRequestBody={type:"object",additionalProperties:false,required:["offeringId","chainId","tokenContractAddress","recordAt","blockNumber","blockHash","confirmations","sourceType","sourceReference","sourceManifestSha256","totalSupplyUnits","holdings"],properties:{offeringId:uuidJson,chainId:{type:"integer",minimum:1},tokenContractAddress:{type:"string",pattern:"^0x[a-fA-F0-9]{40}$"},recordAt:dateJson,blockNumber:integerText,blockHash:{type:"string",pattern:"^0x[a-fA-F0-9]{64}$"},confirmations:{type:"integer",minimum:0},sourceType:{type:"string",enum:["independent_indexer","archive_rpc"]},sourceReference:{type:"string",minLength:3,maxLength:300},sourceManifestSha256:{type:"string",pattern:"^[a-fA-F0-9]{64}$"},totalSupplyUnits:integerText,holdings:{type:"array",minItems:1,maxItems:10000,items:{type:"object",additionalProperties:false,required:["walletAddress","balanceUnits","sourceRowSha256"],properties:{walletAddress:{type:"string",pattern:"^0x[a-fA-F0-9]{40}$"},balanceUnits:integerText,sourceRowSha256:{type:"string",pattern:"^[a-fA-F0-9]{64}$"}}}}}} as const;
const declarationRequestBody={type:"object",additionalProperties:false,required:["offeringId","ownershipSnapshotRequestId","periodLabel","currency","grossAmountMinor","withholdingTaxBps","paymentDueAt"],properties:{offeringId:uuidJson,ownershipSnapshotRequestId:uuidJson,periodLabel:{type:"string",minLength:3,maxLength:120},currency:{type:"string",pattern:"^[A-Za-z]{3}$"},grossAmountMinor:integerText,withholdingTaxBps:{type:"integer",minimum:0,maximum:10000},paymentDueAt:dateJson}} as const;
const decisionRequestBody={type:"object",additionalProperties:false,required:["decision","decisionReason"],properties:{decision:{type:"string",enum:["approve","reject"]},decisionReason:{type:"string",minLength:20,maxLength:2000}}} as const;
const commandResponse={type:"object",additionalProperties:false,required:["requestId","replayed"],properties:{requestId:uuidJson,replayed:{type:"boolean"}}} as const;
const decisionResponse={type:"object",additionalProperties:false,required:["requestId","status","replayed"],properties:{requestId:uuidJson,status:{type:"string",enum:["approved","rejected"]},replayed:{type:"boolean"}}} as const;
const declarationDecisionResponse={type:"object",additionalProperties:false,required:["requestId","status","declarationJournalId","replayed"],properties:{requestId:uuidJson,status:{type:"string",enum:["approved","rejected"]},declarationJournalId:nullable(uuidJson),replayed:{type:"boolean"}}} as const;
const policyOptionsJson={type:"object",additionalProperties:false,required:["policy","currency","rule"],properties:{policy:{type:"object",additionalProperties:false,required:["versionId","versionNumber","reference","name","schemaVersion","jurisdictionCode","legalBasisReference"],properties:{versionId:uuidJson,versionNumber:{type:"integer",minimum:1},reference:text,name:text,schemaVersion:{type:"string",enum:["distribution-policy-v1"]},jurisdictionCode:{type:"string",pattern:"^[A-Z]{2}$"},legalBasisReference:text}},currency:{type:"string",pattern:"^[A-Z]{3}$"},rule:{type:"object",additionalProperties:false,required:["minimumConfirmations","maximumDeclarationMinor","maximumWithholdingTaxBps","retentionDays"],properties:{minimumConfirmations:{type:"integer",minimum:1,maximum:10000},maximumDeclarationMinor:{type:"string",pattern:"^[1-9][0-9]{0,18}$"},maximumWithholdingTaxBps:{type:"integer",minimum:0,maximum:10000},retentionDays:{type:"integer",minimum:1,maximum:9131}}}}} as const;

async function identity(request:FastifyRequest){try{return await requirePostgresIdentityForSubject(request.authUser.userId);}catch(error){if(error instanceof PostgresIdentityUnavailableError)throw new HttpError(409,"Your account migration is not ready for governed distributions.");throw error;}}
function role(request:FastifyRequest,expected:"issuer"|"investor"){if(request.authUser.role!==expected)throw new HttpError(403,`${expected==="issuer"?"Issuer":"Investor"} role required.`);}
async function scope(identityId:string,organizationId:string,roles:readonly("owner"|"administrator"|"offering_manager"|"compliance_reviewer"|"viewer")[]){try{await requireOrganizationAccess({identityId,organizationId,allowedRoles:roles});}catch(error){if(error instanceof TenantAccessError)throw new HttpError(403,"You do not have the required organization role.");throw error;}}
function commandId(request:FastifyRequest){const value=readCommandId(request.headers);if(!value)throw new HttpError(400,"X-Command-ID header is required.");return value;}
function governed<T>(operation:()=>Promise<T>){return operation().catch(error=>{if(error instanceof DistributionAuthorityError)throw new HttpError(error.code==="not_found"?404:error.code==="forbidden"?403:error.code==="invalid_input"?422:409,error.message);throw error;});}

export async function postgresDistributionRoutes(app:FastifyInstance){
  app.get("/v1/governance/organizations/:organizationId/ownership-snapshot-requests",{preHandler:[app.authenticate],schema:{params:idParams("organizationId"),response:{200:{type:"object",additionalProperties:false,required:["requests"],properties:{requests:{type:"array",items:snapshotJson}}},...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"read","distribution");const {organizationId}=orgParams.parse(request.params),identityId=await identity(request);await scope(identityId,organizationId,["owner","administrator","offering_manager","compliance_reviewer","viewer"]);return{requests:await listOwnershipSnapshotRequests(organizationId)};});
  app.post("/v1/governance/organizations/:organizationId/ownership-snapshot-requests",{preHandler:[app.authenticate],schema:{params:idParams("organizationId"),headers:commandHeaders,body:snapshotRequestBody,response:{200:commandResponse,...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"submit","distribution");const {organizationId}=orgParams.parse(request.params),identityId=await identity(request);await scope(identityId,organizationId,["owner","administrator","offering_manager"]);return governed(()=>submitOwnershipSnapshot({organizationId,actorIdentityId:identityId,commandKey:commandId(request),...snapshotBody.parse(request.body)}));});
  app.post("/v1/governance/ownership-snapshot-requests/:requestId/decision",{preHandler:[app.authenticate],schema:{params:idParams("requestId"),body:decisionRequestBody,response:{200:decisionResponse,...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"approve","distribution");const {requestId}=requestParams.parse(request.params),record=await getOwnershipSnapshotRequest(requestId);if(!record)throw new HttpError(404,"Ownership snapshot request not found.");const identityId=await identity(request);await scope(identityId,record.organizationId,["owner","administrator","compliance_reviewer"]);return governed(()=>decideOwnershipSnapshot({requestId,actorIdentityId:identityId,...decisionBody.parse(request.body)}));});
  app.get("/v1/governance/organizations/:organizationId/distribution-policy",{preHandler:[app.authenticate],schema:{params:idParams("organizationId"),querystring:{type:"object",additionalProperties:false,required:["currency"],properties:{currency:{type:"string",pattern:"^[A-Za-z]{3}$"}}},response:{200:policyOptionsJson,...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"read","distribution");const {organizationId}=orgParams.parse(request.params),identityId=await identity(request),{currency}=currencyQuery.parse(request.query);await scope(identityId,organizationId,["owner","administrator","offering_manager","compliance_reviewer","viewer"]);return governed(()=>getDistributionPolicyOptions(organizationId,currency));});
  app.get("/v1/governance/organizations/:organizationId/distribution-declarations",{preHandler:[app.authenticate],schema:{params:idParams("organizationId"),response:{200:{type:"object",additionalProperties:false,required:["requests"],properties:{requests:{type:"array",items:declarationJson}}},...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"read","distribution");const {organizationId}=orgParams.parse(request.params),identityId=await identity(request);await scope(identityId,organizationId,["owner","administrator","offering_manager","compliance_reviewer","viewer"]);return{requests:await listDistributionDeclarations(organizationId)};});
  app.post("/v1/governance/organizations/:organizationId/distribution-declarations",{preHandler:[app.authenticate],schema:{params:idParams("organizationId"),headers:commandHeaders,body:declarationRequestBody,response:{200:commandResponse,...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"submit","distribution");const {organizationId}=orgParams.parse(request.params),identityId=await identity(request);await scope(identityId,organizationId,["owner","administrator","offering_manager"]);return governed(()=>submitDistributionDeclaration({organizationId,actorIdentityId:identityId,commandKey:commandId(request),...declarationBody.parse(request.body)}));});
  app.post("/v1/governance/distribution-declarations/:requestId/decision",{preHandler:[app.authenticate],schema:{params:idParams("requestId"),body:decisionRequestBody,response:{200:declarationDecisionResponse,...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"approve","distribution");const {requestId}=requestParams.parse(request.params),record=await getDistributionDeclaration(requestId);if(!record)throw new HttpError(404,"Distribution declaration request not found.");const identityId=await identity(request);await scope(identityId,record.organizationId,["owner","administrator","compliance_reviewer"]);return governed(()=>decideDistributionDeclaration({requestId,actorIdentityId:identityId,...decisionBody.parse(request.body)}));});
  app.get("/v1/investor/distributions",{preHandler:[app.authenticate],schema:{response:{200:{type:"object",additionalProperties:false,required:["entitlements"],properties:{entitlements:{type:"array",items:entitlementJson}}},...errors}}},async request=>{role(request,"investor");authorize(request.authUser,"read","investor_profile");return{entitlements:await listInvestorDistributionEntitlements(await identity(request))};});
}
