import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import { addDistributionPayoutExceptionEvidence, approveDistributionPayoutExceptionPolicy, createDistributionPayoutExceptionPolicy, decideDistributionFundingRequest, decideDistributionPayoutExceptionHold, decideDistributionPayoutExceptionResolution, DistributionPayoutError, executeDistributionPayoutException, getDistributionFundingRequest, getInvestorDistributionPayoutProfile, listDistributionFundingRequests, listDistributionPayoutReconciliation, openDistributionPayoutException, proposeDistributionPayoutExceptionHold, proposeDistributionPayoutExceptionResolution, submitDistributionFundingRequest, verifyInvestorDistributionPayoutProfile } from "../../../platform/postgres-distribution-payouts.js";
import { getDistributionDeclaration } from "../../../platform/postgres-distributions.js";
import { PostgresIdentityUnavailableError, requirePostgresIdentityForSubject } from "../../../platform/postgres-identities.js";
import { requireOrganizationAccess, TenantAccessError } from "../../../platform/tenant-access.js";
import { HttpError } from "../../../utils/errors.js";
import { readCommandId } from "../../../utils/idempotency.js";
import { authorize } from "../../../utils/rbac.js";

const uuid = z.string().uuid();
const organizationParams = z.object({ organizationId: uuid });
const declarationParams = z.object({ requestId: uuid });
const profileBody = z.object({ bankCode: z.string().trim().min(2).max(20), accountNumber: z.string().regex(/^\d{10}$/) }).strict();
const fundingBody = z.object({ fundingEvidenceReference: z.string().trim().min(4).max(300), fundingEvidenceSha256: z.string().regex(/^[a-fA-F0-9]{64}$/) }).strict();
const decisionBody = z.object({ decision: z.enum(["approve", "reject"]), decisionReason: z.string().trim().min(20).max(2000) }).strict();
const exceptionResolution = z.enum(["replacement_payout", "manual_settlement", "write_off", "close_no_action"]);
const exceptionEvidenceBody = z.object({ evidenceType: z.enum(["provider_verification", "provider_webhook", "bank_confirmation", "investor_confirmation", "fraud_review", "accounting_entry", "legal_basis", "other"]), contentSha256: z.string().regex(/^[a-fA-F0-9]{64}$/), storageKey: z.string().trim().min(1).max(1000), filename: z.string().trim().min(1).max(240), mimeType: z.string().trim().min(3).max(120) }).strict();
const exceptionPolicyBody = z.object({ organizationId: uuid, resolutionType: z.enum(["replacement_payout", "manual_settlement", "write_off"]), currency: z.literal("NGN"), maximumAmountMinor: z.number().int().positive().safe(), effectiveFrom: z.coerce.date(), effectiveUntil: z.coerce.date().optional(), policyReference: z.string().trim().min(8).max(1000) }).strict();
const text = { type: "string" } as const, uuidJson = { type: "string", format: "uuid" } as const, dateJson = { type: "string", format: "date-time" } as const, integerText = { type: "string", pattern: "^[0-9]+$" } as const;
const nullable = (value: object) => ({ anyOf: [value, { type: "null" }] }) as const;
const errors = { 400: { type: "object" }, 401: { type: "object" }, 403: { type: "object" }, 404: { type: "object" }, 409: { type: "object" }, 422: { type: "object" }, 503: { type: "object" } } as const;
const idParams = (key: string) => ({ type: "object", additionalProperties: false, required: [key], properties: { [key]: uuidJson } }) as const;
const commandHeaders = { type: "object", required: ["x-command-id"], properties: { "x-command-id": { type: "string", minLength: 1, maxLength: 200 } } } as const;
const profileJson = { type: "object", additionalProperties: false, required: ["id", "version", "currency", "accountHolderName", "accountLast4", "verifiedAt"], properties: { id: uuidJson, version: { type: "integer", minimum: 1 }, currency: text, accountHolderName: text, accountLast4: text, verifiedAt: dateJson } } as const;
const fundingJson = { type: "object", additionalProperties: false, required: ["id", "reference", "organizationId", "declarationRequestId", "provider", "currency", "amountMinor", "fundingEvidenceReference", "fundingEvidenceSha256", "submissionObservedBalanceMinor", "approvalObservedBalanceMinor", "status", "submittedByIdentityId", "submittedAt", "reviewedByIdentityId", "reviewedAt", "decisionReason"], properties: { id: uuidJson, reference: text, organizationId: uuidJson, declarationRequestId: uuidJson, provider: text, currency: text, amountMinor: integerText, fundingEvidenceReference: text, fundingEvidenceSha256: text, submissionObservedBalanceMinor: integerText, approvalObservedBalanceMinor: nullable(integerText), status: { type: "string", enum: ["submitted", "approved", "rejected"] }, submittedByIdentityId: uuidJson, submittedAt: dateJson, reviewedByIdentityId: nullable(uuidJson), reviewedAt: nullable(dateJson), decisionReason: nullable(text) } } as const;
const reconciliationJson = { type: "object", additionalProperties: false, required: ["id", "reference", "organizationId", "declarationRequestId", "investorIdentityId", "currency", "amountMinor", "status", "authorizedAt", "dispatchStartedAt", "submittedAt", "failedAt", "failureReason", "exceptionCaseId", "exceptionReference", "exceptionStatus", "holdStatus", "resolutionType"], properties: { id: uuidJson, reference: text, organizationId: uuidJson, declarationRequestId: uuidJson, investorIdentityId: uuidJson, currency: text, amountMinor: integerText, status: { type: "string", enum: ["uncertain", "failed", "reversed"] }, authorizedAt: dateJson, dispatchStartedAt: nullable(dateJson), submittedAt: nullable(dateJson), failedAt: nullable(dateJson), failureReason: nullable(text), exceptionCaseId: nullable(uuidJson), exceptionReference: nullable(text), exceptionStatus: nullable(text), holdStatus: nullable(text), resolutionType: nullable(text) } } as const;
const policyBodyJson = { type: "object", additionalProperties: false, required: ["organizationId", "resolutionType", "currency", "maximumAmountMinor", "effectiveFrom", "policyReference"], properties: { organizationId: uuidJson, resolutionType: { type: "string", enum: ["replacement_payout", "manual_settlement", "write_off"] }, currency: { type: "string", enum: ["NGN"] }, maximumAmountMinor: { type: "integer", minimum: 1 }, effectiveFrom: dateJson, effectiveUntil: dateJson, policyReference: { type: "string", minLength: 8, maxLength: 1000 } } } as const;
const evidenceBodyJson = { type: "object", additionalProperties: false, required: ["evidenceType", "contentSha256", "storageKey", "filename", "mimeType"], properties: { evidenceType: { type: "string", enum: ["provider_verification", "provider_webhook", "bank_confirmation", "investor_confirmation", "fraud_review", "accounting_entry", "legal_basis", "other"] }, contentSha256: { type: "string", pattern: "^[a-fA-F0-9]{64}$" }, storageKey: { type: "string", minLength: 1, maxLength: 1000 }, filename: { type: "string", minLength: 1, maxLength: 240 }, mimeType: { type: "string", minLength: 3, maxLength: 120 } } } as const;
const resolutionBodyJson = { type: "object", additionalProperties: false, required: ["resolutionType", "resolutionReason"], properties: { resolutionType: { type: "string", enum: ["replacement_payout", "manual_settlement", "write_off", "close_no_action"] }, resolutionReason: { type: "string", minLength: 20, maxLength: 2000 } } } as const;
const binaryDecisionBodyJson = { type: "object", additionalProperties: false, required: ["decision"], properties: { decision: { type: "string", enum: ["approve", "reject"] } } } as const;
const executeBodyJson = { type: "object", additionalProperties: false, properties: { evidenceReference: { type: "string", minLength: 8, maxLength: 500 } } } as const;
const holdBodyJson = { type: "object", additionalProperties: false, required: ["action", "reason"], properties: { action: { type: "string", enum: ["place", "release"] }, reason: { type: "string", minLength: 20, maxLength: 2000 } } } as const;
const resultJson = (required: readonly string[], properties: Record<string, object>) => ({ type: "object", additionalProperties: false, required, properties }) as const;

async function identity(request: FastifyRequest) { try { return await requirePostgresIdentityForSubject(request.authUser.userId); } catch (error) { if (error instanceof PostgresIdentityUnavailableError) throw new HttpError(409, "Your account migration is not ready for governed distribution payouts."); throw error; } }
async function scope(identityId: string, organizationId: string, roles: readonly ("owner" | "administrator" | "offering_manager" | "compliance_reviewer" | "viewer")[]) { try { await requireOrganizationAccess({ identityId, organizationId, allowedRoles: roles }); } catch (error) { if (error instanceof TenantAccessError) throw new HttpError(403, "You do not have the required organization role."); throw error; } }
function requireRole(request: FastifyRequest, roles: readonly string[]) { if (!roles.includes(request.authUser.role)) throw new HttpError(403, "Your role cannot use this distribution payout route."); }
function commandId(request: FastifyRequest) { const value = readCommandId(request.headers); if (!value) throw new HttpError(400, "X-Command-ID header is required."); return value; }
function governed<T>(operation: () => Promise<T>) { return operation().catch((error) => { if (error instanceof DistributionPayoutError) throw new HttpError(error.code === "not_found" ? 404 : error.code === "forbidden" ? 403 : error.code === "invalid_input" ? 422 : error.code === "provider_unavailable" ? 503 : 409, error.message); throw error; }); }

export async function postgresDistributionPayoutRoutes(app: FastifyInstance) {
  app.get("/v1/investor/distribution-payout-profile", { preHandler: [app.authenticate], schema: { response: { 200: { type: "object", additionalProperties: false, required: ["profile"], properties: { profile: nullable(profileJson) } }, ...errors } } }, async (request) => { requireRole(request, ["investor"]); authorize(request.authUser, "read", "investor_profile"); return { profile: await getInvestorDistributionPayoutProfile(await identity(request)) }; });
  app.post("/v1/investor/distribution-payout-profile", { preHandler: [app.authenticate], schema: { body: { type: "object", additionalProperties: false, required: ["bankCode", "accountNumber"], properties: { bankCode: { type: "string", minLength: 2, maxLength: 20 }, accountNumber: { type: "string", pattern: "^[0-9]{10}$" } } }, response: { 200: { type: "object", additionalProperties: false, required: ["payoutProfileVersionId", "version", "currency", "accountHolderName", "accountLast4"], properties: { payoutProfileVersionId: uuidJson, version: { type: "integer" }, currency: text, accountHolderName: text, accountLast4: text } }, ...errors } } }, async (request) => { requireRole(request, ["investor"]); authorize(request.authUser, "update", "investor_profile"); const investorIdentityId = await identity(request); return governed(() => verifyInvestorDistributionPayoutProfile({ investorIdentityId, ...profileBody.parse(request.body) })); });
  app.get("/v1/governance/organizations/:organizationId/distribution-funding-requests", { preHandler: [app.authenticate], schema: { params: idParams("organizationId"), response: { 200: { type: "object", additionalProperties: false, required: ["requests"], properties: { requests: { type: "array", items: fundingJson } } }, ...errors } } }, async (request) => { requireRole(request, ["issuer"]); authorize(request.authUser, "read", "distribution"); const { organizationId } = organizationParams.parse(request.params), identityId = await identity(request); await scope(identityId, organizationId, ["owner", "administrator", "offering_manager", "compliance_reviewer", "viewer"]); return { requests: await listDistributionFundingRequests(organizationId) }; });
  app.post("/v1/governance/distribution-declarations/:requestId/funding-requests", { preHandler: [app.authenticate], schema: { params: idParams("requestId"), headers: commandHeaders, body: { type: "object", additionalProperties: false, required: ["fundingEvidenceReference", "fundingEvidenceSha256"], properties: { fundingEvidenceReference: { type: "string", minLength: 4, maxLength: 300 }, fundingEvidenceSha256: { type: "string", pattern: "^[a-fA-F0-9]{64}$" } } }, response: { 200: { type: "object", additionalProperties: false, required: ["requestId", "replayed"], properties: { requestId: uuidJson, replayed: { type: "boolean" } } }, ...errors } } }, async (request) => { requireRole(request, ["issuer"]); authorize(request.authUser, "submit", "distribution"); const declarationRequestId = declarationParams.parse(request.params).requestId, record = await getDistributionDeclaration(declarationRequestId); if (!record) throw new HttpError(404, "Distribution declaration not found."); const actorIdentityId = await identity(request); await scope(actorIdentityId, record.organizationId, ["owner", "administrator", "offering_manager"]); return governed(() => submitDistributionFundingRequest({ organizationId: record.organizationId, declarationRequestId, actorIdentityId, commandKey: commandId(request), ...fundingBody.parse(request.body) })); });
  app.post("/v1/governance/distribution-funding-requests/:requestId/decision", { preHandler: [app.authenticate], schema: { params: idParams("requestId"), body: { type: "object", additionalProperties: false, required: ["decision", "decisionReason"], properties: { decision: { type: "string", enum: ["approve", "reject"] }, decisionReason: { type: "string", minLength: 20, maxLength: 2000 } } }, response: { 200: { type: "object", additionalProperties: false, required: ["requestId", "status", "instructionCount", "replayed"], properties: { requestId: uuidJson, status: { type: "string", enum: ["approved", "rejected"] }, instructionCount: { type: "integer", minimum: 0 }, replayed: { type: "boolean" } } }, ...errors } } }, async (request) => { requireRole(request, ["issuer"]); authorize(request.authUser, "approve", "distribution"); const requestId = declarationParams.parse(request.params).requestId, record = await getDistributionFundingRequest(requestId); if (!record) throw new HttpError(404, "Distribution funding request not found."); const actorIdentityId = await identity(request); await scope(actorIdentityId, record.organizationId, ["owner", "administrator", "compliance_reviewer"]); return governed(() => decideDistributionFundingRequest({ requestId, actorIdentityId, ...decisionBody.parse(request.body) })); });
  app.get("/v1/control/distribution-payout-reconciliation", { preHandler: [app.authenticate], schema: { response: { 200: { type: "object", additionalProperties: false, required: ["items"], properties: { items: { type: "array", items: reconciliationJson } } }, ...errors } } }, async (request) => { requireRole(request, ["operator", "admin"]); authorize(request.authUser, "read", "reconciliation"); return { items: await listDistributionPayoutReconciliation() }; });
  app.post("/v1/control/distribution-payout-exceptions/policies", { preHandler: [app.authenticate], schema: { body: policyBodyJson, response: { 200: resultJson(["policyId","version"],{policyId:uuidJson,version:{type:"integer",minimum:1}}), ...errors } } }, async (request) => { requireRole(request, ["operator", "admin"]); const actorIdentityId = await identity(request); return governed(() => createDistributionPayoutExceptionPolicy({ ...exceptionPolicyBody.parse(request.body), actorIdentityId })); });
  app.post("/v1/control/distribution-payout-exceptions/policies/:policyId/approve", { preHandler: [app.authenticate], schema: { params: idParams("policyId"), response: { 200: resultJson(["policyId","status"],{policyId:uuidJson,status:{type:"string",enum:["active"]}}), ...errors } } }, async (request) => { requireRole(request, ["operator", "admin"]); const actorIdentityId = await identity(request), policyId = z.object({ policyId: uuid }).parse(request.params).policyId; return governed(() => approveDistributionPayoutExceptionPolicy({ policyId, actorIdentityId })); });
  app.post("/v1/control/distribution-payout-exceptions/payouts/:payoutInstructionId", { preHandler: [app.authenticate], schema: { params: idParams("payoutInstructionId"), response: { 200: resultJson(["exceptionCaseId","replayed"],{exceptionCaseId:uuidJson,replayed:{type:"boolean"}}), ...errors } } }, async (request) => { requireRole(request, ["operator", "admin"]); const actorIdentityId = await identity(request), payoutInstructionId = z.object({ payoutInstructionId: uuid }).parse(request.params).payoutInstructionId; return governed(() => openDistributionPayoutException({ payoutInstructionId, actorIdentityId })); });
  app.post("/v1/control/distribution-payout-exceptions/:exceptionCaseId/evidence", { preHandler: [app.authenticate], schema: { params: idParams("exceptionCaseId"), body: evidenceBodyJson, response: { 200: resultJson(["evidenceId"],{evidenceId:uuidJson}), ...errors } } }, async (request) => { requireRole(request, ["operator", "admin"]); const actorIdentityId = await identity(request), exceptionCaseId = z.object({ exceptionCaseId: uuid }).parse(request.params).exceptionCaseId; return governed(() => addDistributionPayoutExceptionEvidence({ exceptionCaseId, actorIdentityId, ...exceptionEvidenceBody.parse(request.body) })); });
  app.post("/v1/control/distribution-payout-exceptions/:exceptionCaseId/resolution", { preHandler: [app.authenticate], schema: { params: idParams("exceptionCaseId"), body: resolutionBodyJson, response: { 200: resultJson(["exceptionCaseId","status"],{exceptionCaseId:uuidJson,status:{type:"string",enum:["decision_pending"]}}), ...errors } } }, async (request) => { requireRole(request, ["operator", "admin"]); const actorIdentityId = await identity(request), exceptionCaseId = z.object({ exceptionCaseId: uuid }).parse(request.params).exceptionCaseId, body = z.object({ resolutionType: exceptionResolution, resolutionReason: z.string().trim().min(20).max(2000) }).strict().parse(request.body); return governed(() => proposeDistributionPayoutExceptionResolution({ exceptionCaseId, actorIdentityId, ...body })); });
  app.post("/v1/control/distribution-payout-exceptions/:exceptionCaseId/decision", { preHandler: [app.authenticate], schema: { params: idParams("exceptionCaseId"), body: binaryDecisionBodyJson, response: { 200: resultJson(["exceptionCaseId","status"],{exceptionCaseId:uuidJson,status:{type:"string",enum:["approved","rejected"]}}), ...errors } } }, async (request) => { requireRole(request, ["operator", "admin"]); const actorIdentityId = await identity(request), exceptionCaseId = z.object({ exceptionCaseId: uuid }).parse(request.params).exceptionCaseId, body = z.object({ decision: z.enum(["approve", "reject"]) }).strict().parse(request.body); return governed(() => decideDistributionPayoutExceptionResolution({ exceptionCaseId, actorIdentityId, approve: body.decision === "approve" })); });
  app.post("/v1/control/distribution-payout-exceptions/:exceptionCaseId/execute", { preHandler: [app.authenticate], schema: { params: idParams("exceptionCaseId"), body: executeBodyJson, response: { 200: resultJson(["exceptionCaseId","executionId","resolutionType","replacementPayoutInstructionId","correctionJournalId"],{exceptionCaseId:uuidJson,executionId:uuidJson,resolutionType:text,replacementPayoutInstructionId:nullable(uuidJson),correctionJournalId:nullable(uuidJson)}), ...errors } } }, async (request) => { requireRole(request, ["operator", "admin"]); const actorIdentityId = await identity(request), exceptionCaseId = z.object({ exceptionCaseId: uuid }).parse(request.params).exceptionCaseId, body = z.object({ evidenceReference: z.string().trim().min(8).max(500).optional() }).strict().parse(request.body); return governed(() => executeDistributionPayoutException({ exceptionCaseId, actorIdentityId, ...body })); });
  app.post("/v1/control/distribution-payout-exceptions/:exceptionCaseId/hold-requests", { preHandler: [app.authenticate], schema: { params: idParams("exceptionCaseId"), body: holdBodyJson, response: { 200: resultJson(["holdRequestId","status"],{holdRequestId:uuidJson,status:{type:"string",enum:["pending"]}}), ...errors } } }, async (request) => { requireRole(request, ["operator", "admin"]); const actorIdentityId = await identity(request), exceptionCaseId = z.object({ exceptionCaseId: uuid }).parse(request.params).exceptionCaseId, body = z.object({ action: z.enum(["place", "release"]), reason: z.string().trim().min(20).max(2000) }).strict().parse(request.body); return governed(() => proposeDistributionPayoutExceptionHold({ exceptionCaseId, actorIdentityId, ...body })); });
  app.post("/v1/control/distribution-payout-exceptions/hold-requests/:holdRequestId/decision", { preHandler: [app.authenticate], schema: { params: idParams("holdRequestId"), body: binaryDecisionBodyJson, response: { 200: resultJson(["holdRequestId","status"],{holdRequestId:uuidJson,status:{type:"string",enum:["approved","rejected"]},holdStatus:{type:"string",enum:["active","clear"]}}), ...errors } } }, async (request) => { requireRole(request, ["operator", "admin"]); const actorIdentityId = await identity(request), holdRequestId = z.object({ holdRequestId: uuid }).parse(request.params).holdRequestId, body = z.object({ decision: z.enum(["approve", "reject"]) }).strict().parse(request.body); return governed(() => decideDistributionPayoutExceptionHold({ holdRequestId, actorIdentityId, approve: body.decision === "approve" })); });
}
