import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import { approveDistributionTaxPolicy, createDistributionTaxPolicy, decideDistributionTaxFiling, decideDistributionTaxPayment, decideDistributionTaxRemittanceReversal, DistributionTaxError, getDistributionTaxPolicy, getDistributionTaxRemittance, getDistributionTaxRemittanceReversal, listDistributionTaxPolicies, listDistributionTaxRemittances, listInvestorDistributionTaxStatements, proposeDistributionTaxRemittanceReversal, submitDistributionTaxPaymentEvidence, submitDistributionTaxRemittance } from "../../../platform/postgres-distribution-tax.js";
import { getDistributionDeclaration } from "../../../platform/postgres-distributions.js";
import { PostgresIdentityUnavailableError, requirePostgresIdentityForSubject } from "../../../platform/postgres-identities.js";
import { requireOrganizationAccess, TenantAccessError } from "../../../platform/tenant-access.js";
import { HttpError } from "../../../utils/errors.js";
import { authorize } from "../../../utils/rbac.js";

const uuid=z.string().uuid(),orgParams=z.object({organizationId:uuid}),requestParams=z.object({requestId:uuid}),policyParams=z.object({policyId:uuid}),declarationParams=z.object({declarationRequestId:uuid});
const policyBody=z.object({jurisdictionCode:z.string().regex(/^[A-Za-z]{2}$/),currency:z.string().regex(/^[A-Za-z]{3}$/),taxAuthorityName:z.string().trim().min(3).max(240),taxAuthorityReference:z.string().trim().min(8).max(1000),filingDueDays:z.number().int().min(0).max(366),paymentDueDays:z.number().int().min(0).max(366),effectiveFrom:z.coerce.date(),effectiveUntil:z.coerce.date().optional()}).strict();
const submitBody=z.object({taxPeriodStart:z.coerce.date(),taxPeriodEnd:z.coerce.date(),filingReference:z.string().trim().min(8).max(500),filingEvidenceSha256:z.string().regex(/^[a-fA-F0-9]{64}$/)}).strict();
const decisionBody=z.object({decision:z.enum(["approve","reject"]),decisionReason:z.string().trim().min(20).max(2000)}).strict();
const paymentBody=z.object({paymentReference:z.string().trim().min(8).max(500),paymentEvidenceSha256:z.string().regex(/^[a-fA-F0-9]{64}$/)}).strict();
const paymentDecisionBody=decisionBody.extend({authorityReceiptReference:z.string().trim().min(8).max(500).optional(),authorityReceiptSha256:z.string().regex(/^[a-fA-F0-9]{64}$/).optional()}).strict().superRefine((value,ctx)=>{if(value.decision==="approve"&&(!value.authorityReceiptReference||!value.authorityReceiptSha256))ctx.addIssue({code:z.ZodIssueCode.custom,message:"Authority receipt evidence is required for confirmed remittance."});});
const reversalBody=z.object({reason:z.string().trim().min(20).max(2000)}).strict();
const text={type:"string"} as const,uuidJson={type:"string",format:"uuid"} as const,dateJson={type:"string",format:"date-time"} as const,dateOnlyJson={type:"string",format:"date"} as const,integerText={type:"string",pattern:"^[0-9]+$"} as const;
const nullable=(value:object)=>({anyOf:[value,{type:"null"}]}) as const,idParams=(key:string)=>({type:"object",additionalProperties:false,required:[key],properties:{[key]:uuidJson}}) as const;
const errors={400:{type:"object"},401:{type:"object"},403:{type:"object"},404:{type:"object"},409:{type:"object"},422:{type:"object"}} as const;
const decisionJson={type:"object",additionalProperties:false,required:["decision","decisionReason"],properties:{decision:{type:"string",enum:["approve","reject"]},decisionReason:{type:"string",minLength:20,maxLength:2000}}} as const;
const policyBodyJson={type:"object",additionalProperties:false,required:["jurisdictionCode","currency","taxAuthorityName","taxAuthorityReference","filingDueDays","paymentDueDays","effectiveFrom"],properties:{jurisdictionCode:{type:"string",pattern:"^[A-Za-z]{2}$"},currency:{type:"string",pattern:"^[A-Za-z]{3}$"},taxAuthorityName:{type:"string",minLength:3,maxLength:240},taxAuthorityReference:{type:"string",minLength:8,maxLength:1000},filingDueDays:{type:"integer",minimum:0,maximum:366},paymentDueDays:{type:"integer",minimum:0,maximum:366},effectiveFrom:dateJson,effectiveUntil:dateJson}} as const;
const submitBodyJson={type:"object",additionalProperties:false,required:["taxPeriodStart","taxPeriodEnd","filingReference","filingEvidenceSha256"],properties:{taxPeriodStart:dateOnlyJson,taxPeriodEnd:dateOnlyJson,filingReference:{type:"string",minLength:8,maxLength:500},filingEvidenceSha256:{type:"string",pattern:"^[a-fA-F0-9]{64}$"}}} as const;
const paymentBodyJson={type:"object",additionalProperties:false,required:["paymentReference","paymentEvidenceSha256"],properties:{paymentReference:{type:"string",minLength:8,maxLength:500},paymentEvidenceSha256:{type:"string",pattern:"^[a-fA-F0-9]{64}$"}}} as const;
const paymentDecisionJson={type:"object",additionalProperties:false,required:["decision","decisionReason"],properties:{...decisionJson.properties,authorityReceiptReference:{type:"string",minLength:8,maxLength:500},authorityReceiptSha256:{type:"string",pattern:"^[a-fA-F0-9]{64}$"}}} as const;
const remittanceJson={type:"object",additionalProperties:false,required:["id","reference","organizationId","declarationRequestId","policyId","jurisdictionCode","currency","amountMinor","taxPeriodStart","taxPeriodEnd","filingDueAt","paymentDueAt","filingReference","filingEvidenceSha256","paymentReference","paymentEvidenceSha256","authorityReceiptReference","authorityReceiptSha256","status","submittedByIdentityId","reviewedByIdentityId","paymentSubmittedByIdentityId","paymentReviewedByIdentityId","submittedAt","reviewedAt","paymentSubmittedAt","paymentReviewedAt","remittedAt","reversedAt","decisionReason","remittanceJournalId","reversalJournalId","pendingReversalRequestId","pendingReversalStatus"],properties:{id:uuidJson,reference:text,organizationId:uuidJson,declarationRequestId:uuidJson,policyId:uuidJson,jurisdictionCode:text,currency:text,amountMinor:integerText,taxPeriodStart:dateOnlyJson,taxPeriodEnd:dateOnlyJson,filingDueAt:dateJson,paymentDueAt:dateJson,filingReference:text,filingEvidenceSha256:text,paymentReference:nullable(text),paymentEvidenceSha256:nullable(text),authorityReceiptReference:nullable(text),authorityReceiptSha256:nullable(text),status:{type:"string",enum:["submitted","approved","rejected","payment_evidence_submitted","remitted","payment_rejected","reversed"]},submittedByIdentityId:uuidJson,reviewedByIdentityId:nullable(uuidJson),paymentSubmittedByIdentityId:nullable(uuidJson),paymentReviewedByIdentityId:nullable(uuidJson),submittedAt:dateJson,reviewedAt:nullable(dateJson),paymentSubmittedAt:nullable(dateJson),paymentReviewedAt:nullable(dateJson),remittedAt:nullable(dateJson),reversedAt:nullable(dateJson),decisionReason:nullable(text),remittanceJournalId:nullable(uuidJson),reversalJournalId:nullable(uuidJson),pendingReversalRequestId:nullable(uuidJson),pendingReversalStatus:nullable(text)}} as const;
const statementJson={type:"object",additionalProperties:false,required:["id","reference","declarationRequestId","distributionReference","organizationName","periodLabel","jurisdictionCode","currency","grossAmountMinor","withholdingTaxMinor","taxPeriodStart","taxPeriodEnd","taxAuthorityName","authorityReceiptReference","legalBasisReference","statementSha256","status","issuedAt","revokedAt"],properties:{id:uuidJson,reference:text,declarationRequestId:uuidJson,distributionReference:text,organizationName:text,periodLabel:text,jurisdictionCode:text,currency:text,grossAmountMinor:integerText,withholdingTaxMinor:integerText,taxPeriodStart:dateOnlyJson,taxPeriodEnd:dateOnlyJson,taxAuthorityName:text,authorityReceiptReference:text,legalBasisReference:text,statementSha256:text,status:{type:"string",enum:["active","revoked"]},issuedAt:dateJson,revokedAt:nullable(dateJson)}} as const;
const taxPolicyJson={type:"object",additionalProperties:false,required:["id","version","jurisdictionCode","currency","taxAuthorityName","taxAuthorityReference","filingDueDays","paymentDueDays","effectiveFrom","effectiveUntil","status","preparedByIdentityId","approvedByIdentityId","approvedAt"],properties:{id:uuidJson,version:{type:"integer",minimum:1},jurisdictionCode:text,currency:text,taxAuthorityName:text,taxAuthorityReference:text,filingDueDays:{type:"integer"},paymentDueDays:{type:"integer"},effectiveFrom:dateJson,effectiveUntil:nullable(dateJson),status:{type:"string",enum:["draft","active","superseded"]},preparedByIdentityId:uuidJson,approvedByIdentityId:nullable(uuidJson),approvedAt:nullable(dateJson)}} as const;
const resultJson=(required:readonly string[],properties:Record<string,object>)=>({type:"object",additionalProperties:false,required,properties}) as const;

async function identity(request:FastifyRequest){try{return await requirePostgresIdentityForSubject(request.authUser.userId);}catch(error){if(error instanceof PostgresIdentityUnavailableError)throw new HttpError(409,"Your account migration is not ready for governed tax records.");throw error;}}
function role(request:FastifyRequest,expected:"issuer"|"investor"){if(request.authUser.role!==expected)throw new HttpError(403,`${expected==="issuer"?"Issuer":"Investor"} role required.`);}
async function scope(identityId:string,organizationId:string,roles:readonly("owner"|"administrator"|"offering_manager"|"compliance_reviewer"|"viewer")[]){try{await requireOrganizationAccess({identityId,organizationId,allowedRoles:roles});}catch(error){if(error instanceof TenantAccessError)throw new HttpError(403,"You do not have the required organization role.");throw error;}}
function governed<T>(operation:()=>Promise<T>){return operation().catch(error=>{if(error instanceof DistributionTaxError)throw new HttpError(error.code==="not_found"?404:error.code==="forbidden"?403:error.code==="invalid_input"?422:409,error.message);throw error;});}
async function requestScope(requestId:string,identityId:string,roles:readonly("owner"|"administrator"|"offering_manager"|"compliance_reviewer"|"viewer")[]){const record=await getDistributionTaxRemittance(requestId);if(!record)throw new HttpError(404,"Tax remittance request not found.");await scope(identityId,record.organizationId,roles);return record;}

export async function postgresDistributionTaxRoutes(app:FastifyInstance){
  app.get("/v1/governance/organizations/:organizationId/distribution-tax-remittances",{preHandler:[app.authenticate],schema:{params:idParams("organizationId"),response:{200:{type:"object",additionalProperties:false,required:["requests"],properties:{requests:{type:"array",items:remittanceJson}}},...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"read","distribution");const {organizationId}=orgParams.parse(request.params),actor=await identity(request);await scope(actor,organizationId,["owner","administrator","offering_manager","compliance_reviewer","viewer"]);return{requests:await listDistributionTaxRemittances(organizationId)};});
  app.get("/v1/governance/organizations/:organizationId/distribution-tax-policies",{preHandler:[app.authenticate],schema:{params:idParams("organizationId"),response:{200:{type:"object",additionalProperties:false,required:["policies"],properties:{policies:{type:"array",items:taxPolicyJson}}},...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"read","distribution");const {organizationId}=orgParams.parse(request.params),actor=await identity(request);await scope(actor,organizationId,["owner","administrator","offering_manager","compliance_reviewer","viewer"]);return{policies:await listDistributionTaxPolicies(organizationId)};});
  app.post("/v1/governance/organizations/:organizationId/distribution-tax-policies",{preHandler:[app.authenticate],schema:{params:idParams("organizationId"),body:policyBodyJson,response:{200:resultJson(["policyId","version"],{policyId:uuidJson,version:{type:"integer",minimum:1}}),...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"submit","distribution");const {organizationId}=orgParams.parse(request.params),actor=await identity(request);await scope(actor,organizationId,["owner","administrator"]);return governed(()=>createDistributionTaxPolicy({organizationId,actorIdentityId:actor,...policyBody.parse(request.body)}));});
  app.post("/v1/governance/distribution-tax-policies/:policyId/approve",{preHandler:[app.authenticate],schema:{params:idParams("policyId"),response:{200:resultJson(["policyId","status"],{policyId:uuidJson,status:{type:"string",enum:["active"]}}),...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"approve","distribution");const {policyId}=policyParams.parse(request.params),actor=await identity(request),policy=await getDistributionTaxPolicy(policyId);if(!policy)throw new HttpError(404,"Tax policy not found.");await scope(actor,policy.organizationId,["owner","administrator","compliance_reviewer"]);return governed(()=>approveDistributionTaxPolicy({policyId,actorIdentityId:actor}));});
  app.post("/v1/governance/distribution-declarations/:declarationRequestId/tax-remittance",{preHandler:[app.authenticate],schema:{params:idParams("declarationRequestId"),body:submitBodyJson,response:{200:resultJson(["requestId"],{requestId:uuidJson}),...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"submit","distribution");const {declarationRequestId}=declarationParams.parse(request.params),declaration=await getDistributionDeclaration(declarationRequestId);if(!declaration)throw new HttpError(404,"Distribution declaration not found.");const actor=await identity(request);await scope(actor,declaration.organizationId,["owner","administrator","offering_manager"]);return governed(()=>submitDistributionTaxRemittance({organizationId:declaration.organizationId,declarationRequestId,actorIdentityId:actor,...submitBody.parse(request.body)}));});
  app.post("/v1/governance/distribution-tax-remittances/:requestId/filing-decision",{preHandler:[app.authenticate],schema:{params:idParams("requestId"),body:decisionJson,response:{200:resultJson(["requestId","status"],{requestId:uuidJson,status:{type:"string",enum:["approved","rejected"]}}),...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"approve","distribution");const {requestId}=requestParams.parse(request.params),actor=await identity(request);await requestScope(requestId,actor,["owner","administrator","compliance_reviewer"]);const body=decisionBody.parse(request.body);return governed(()=>decideDistributionTaxFiling({requestId,actorIdentityId:actor,approve:body.decision==="approve",decisionReason:body.decisionReason}));});
  app.post("/v1/governance/distribution-tax-remittances/:requestId/payment-evidence",{preHandler:[app.authenticate],schema:{params:idParams("requestId"),body:paymentBodyJson,response:{200:resultJson(["requestId","status"],{requestId:uuidJson,status:{type:"string",enum:["payment_evidence_submitted"]}}),...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"submit","distribution");const {requestId}=requestParams.parse(request.params),actor=await identity(request);await requestScope(requestId,actor,["owner","administrator","offering_manager"]);return governed(()=>submitDistributionTaxPaymentEvidence({requestId,actorIdentityId:actor,...paymentBody.parse(request.body)}));});
  app.post("/v1/governance/distribution-tax-remittances/:requestId/payment-decision",{preHandler:[app.authenticate],schema:{params:idParams("requestId"),body:paymentDecisionJson,response:{200:resultJson(["requestId","status","remittanceJournalId"],{requestId:uuidJson,status:{type:"string",enum:["remitted","payment_rejected"]},remittanceJournalId:nullable(uuidJson)}),...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"approve","distribution");const {requestId}=requestParams.parse(request.params),actor=await identity(request);await requestScope(requestId,actor,["owner","administrator","compliance_reviewer"]);const body=paymentDecisionBody.parse(request.body);return governed(()=>decideDistributionTaxPayment({requestId,actorIdentityId:actor,approve:body.decision==="approve",decisionReason:body.decisionReason,authorityReceiptReference:body.authorityReceiptReference,authorityReceiptSha256:body.authorityReceiptSha256}));});
  app.post("/v1/governance/distribution-tax-remittances/:requestId/reversal-requests",{preHandler:[app.authenticate],schema:{params:idParams("requestId"),body:{type:"object",additionalProperties:false,required:["reason"],properties:{reason:{type:"string",minLength:20,maxLength:2000}}},response:{200:resultJson(["reversalRequestId","status"],{reversalRequestId:uuidJson,status:{type:"string",enum:["pending"]}}),...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"submit","distribution");const {requestId}=requestParams.parse(request.params),actor=await identity(request);await requestScope(requestId,actor,["owner","administrator","offering_manager"]);return governed(()=>proposeDistributionTaxRemittanceReversal({requestId,actorIdentityId:actor,...reversalBody.parse(request.body)}));});
  app.post("/v1/governance/distribution-tax-remittance-reversals/:reversalRequestId/decision",{preHandler:[app.authenticate],schema:{params:idParams("reversalRequestId"),body:{type:"object",additionalProperties:false,required:["decision"],properties:{decision:{type:"string",enum:["approve","reject"]}}},response:{200:resultJson(["reversalRequestId","status","reversalJournalId"],{reversalRequestId:uuidJson,status:{type:"string",enum:["executed","rejected"]},reversalJournalId:nullable(uuidJson)}),...errors}}},async request=>{role(request,"issuer");authorize(request.authUser,"approve","distribution");const {reversalRequestId}=z.object({reversalRequestId:uuid}).parse(request.params),actor=await identity(request),body=z.object({decision:z.enum(["approve","reject"])}).strict().parse(request.body),record=await getDistributionTaxRemittanceReversal(reversalRequestId);if(!record)throw new HttpError(404,"Tax remittance reversal request not found.");await scope(actor,record.organizationId,["owner","administrator","compliance_reviewer"]);return governed(()=>decideDistributionTaxRemittanceReversal({reversalRequestId,actorIdentityId:actor,approve:body.decision==="approve"}));});
  app.get("/v1/investor/distribution-tax-statements",{preHandler:[app.authenticate],schema:{response:{200:{type:"object",additionalProperties:false,required:["statements"],properties:{statements:{type:"array",items:statementJson}}},...errors}}},async request=>{role(request,"investor");authorize(request.authUser,"read","investor_profile");return{statements:await listInvestorDistributionTaxStatements(await identity(request))};});
}
