import type { PostgresMigration } from "./types.js";

/**
 * Establishes one authoritative issuer-organization boundary. Organization
 * profile claims are snapshots reviewed independently; invitation bearer
 * material is generated by a leased delivery worker rather than returned by
 * the browser command; and the database protects the final active owner.
 */
export const organizationAuthorityMigration: PostgresMigration = {
  version: "061-organization-authority",
  sql: `
    ALTER TABLE fractal.organizations
      ADD COLUMN IF NOT EXISTS created_by_identity_id UUID REFERENCES fractal.identities(id),
      ADD COLUMN IF NOT EXISTS jurisdiction_code VARCHAR(2),
      ADD COLUMN IF NOT EXISTS entity_type TEXT,
      ADD COLUMN IF NOT EXISTS primary_activity TEXT,
      ADD COLUMN IF NOT EXISTS registered_address JSONB,
      ADD COLUMN IF NOT EXISTS verification_status TEXT NOT NULL DEFAULT 'not_started',
      ADD COLUMN IF NOT EXISTS verification_version INTEGER NOT NULL DEFAULT 0,
      ADD COLUMN IF NOT EXISTS verification_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ,
      ADD COLUMN IF NOT EXISTS verified_by_identity_id UUID REFERENCES fractal.identities(id),
      ADD COLUMN IF NOT EXISTS verification_expires_at TIMESTAMPTZ;

    ALTER TABLE fractal.organizations
      DROP CONSTRAINT IF EXISTS organizations_jurisdiction_code_check,
      ADD CONSTRAINT organizations_jurisdiction_code_check
        CHECK (jurisdiction_code IS NULL OR jurisdiction_code ~ '^[A-Z]{2}$'),
      DROP CONSTRAINT IF EXISTS organizations_entity_type_check,
      ADD CONSTRAINT organizations_entity_type_check
        CHECK (entity_type IS NULL OR entity_type IN ('private_company', 'public_company', 'partnership', 'trust', 'special_purpose_vehicle', 'cooperative', 'other')),
      DROP CONSTRAINT IF EXISTS organizations_primary_activity_check,
      ADD CONSTRAINT organizations_primary_activity_check
        CHECK (primary_activity IS NULL OR length(primary_activity) BETWEEN 2 AND 500),
      DROP CONSTRAINT IF EXISTS organizations_registered_address_check,
      ADD CONSTRAINT organizations_registered_address_check
        CHECK (registered_address IS NULL OR jsonb_typeof(registered_address) = 'object'),
      DROP CONSTRAINT IF EXISTS organizations_verification_status_check,
      ADD CONSTRAINT organizations_verification_status_check
        CHECK (verification_status IN ('not_started', 'pending', 'verified', 'rejected', 'expired', 'suspended')),
      DROP CONSTRAINT IF EXISTS organizations_verification_version_check,
      ADD CONSTRAINT organizations_verification_version_check
        CHECK (verification_version >= 0),
      DROP CONSTRAINT IF EXISTS organizations_verified_shape,
      ADD CONSTRAINT organizations_verified_shape CHECK (
        (verification_status = 'verified'
          AND verification_version > 0
          AND verified_at IS NOT NULL
          AND verified_by_identity_id IS NOT NULL
          AND verification_expires_at IS NOT NULL
          AND verification_expires_at > verified_at)
        OR verification_status <> 'verified'
      );
    CREATE UNIQUE INDEX IF NOT EXISTS organizations_registration_normalized_unique_idx
      ON fractal.organizations (upper(registration_number))
      WHERE registration_number IS NOT NULL;

    CREATE TABLE IF NOT EXISTS fractal.organization_verification_evidence_documents (
      id UUID PRIMARY KEY,
      organization_id UUID NOT NULL REFERENCES fractal.organizations(id),
      evidence_type TEXT NOT NULL CHECK (evidence_type IN ('registration_evidence', 'registry_extract', 'registered_address', 'ownership_structure', 'representative_authority', 'tax_registration', 'other')),
      filename TEXT NOT NULL CHECK (length(filename) BETWEEN 1 AND 240),
      mime_type TEXT NOT NULL CHECK (length(mime_type) BETWEEN 3 AND 120),
      storage_key TEXT NOT NULL UNIQUE CHECK (length(storage_key) BETWEEN 1 AND 1000),
      content_sha256 CHAR(64) NOT NULL CHECK (content_sha256 ~ '^[a-f0-9]{64}$'),
      bytes BIGINT NOT NULL CHECK (bytes > 0),
      uploaded_by_identity_id UUID NOT NULL REFERENCES fractal.identities(id),
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      UNIQUE (id, organization_id, evidence_type)
    );
    CREATE INDEX IF NOT EXISTS organization_verification_evidence_org_idx
      ON fractal.organization_verification_evidence_documents (organization_id, created_at DESC, id DESC);

    CREATE TABLE IF NOT EXISTS fractal.organization_verification_requests (
      id UUID PRIMARY KEY,
      organization_id UUID NOT NULL REFERENCES fractal.organizations(id),
      version INTEGER NOT NULL CHECK (version > 0),
      legal_name TEXT NOT NULL CHECK (length(legal_name) BETWEEN 2 AND 240),
      registration_number TEXT NOT NULL CHECK (length(registration_number) BETWEEN 2 AND 120),
      jurisdiction_code VARCHAR(2) NOT NULL CHECK (jurisdiction_code ~ '^[A-Z]{2}$'),
      entity_type TEXT NOT NULL CHECK (entity_type IN ('private_company', 'public_company', 'partnership', 'trust', 'special_purpose_vehicle', 'cooperative', 'other')),
      primary_activity TEXT NOT NULL CHECK (length(primary_activity) BETWEEN 2 AND 500),
      registered_address JSONB NOT NULL CHECK (jsonb_typeof(registered_address) = 'object'),
      representative_authority_basis TEXT NOT NULL CHECK (length(representative_authority_basis) BETWEEN 10 AND 2000),
      status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'under_review', 'approved', 'rejected', 'superseded')),
      submitted_by_identity_id UUID NOT NULL REFERENCES fractal.identities(id),
      submitted_at TIMESTAMPTZ,
      decided_by_identity_id UUID REFERENCES fractal.identities(id),
      decided_at TIMESTAMPTZ,
      decision_reason TEXT CHECK (decision_reason IS NULL OR length(decision_reason) BETWEEN 10 AND 2000),
      verification_expires_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      UNIQUE (organization_id, version),
      UNIQUE (id, organization_id),
      CONSTRAINT organization_verification_independent_reviewer CHECK (
        decided_by_identity_id IS NULL OR decided_by_identity_id <> submitted_by_identity_id
      ),
      CONSTRAINT organization_verification_request_status_shape CHECK (
        (status = 'draft' AND submitted_at IS NULL AND decided_by_identity_id IS NULL AND decided_at IS NULL AND decision_reason IS NULL AND verification_expires_at IS NULL)
        OR (status IN ('submitted', 'under_review') AND submitted_at IS NOT NULL AND decided_by_identity_id IS NULL AND decided_at IS NULL AND decision_reason IS NULL AND verification_expires_at IS NULL)
        OR (status = 'approved' AND submitted_at IS NOT NULL AND decided_by_identity_id IS NOT NULL AND decided_at IS NOT NULL AND decision_reason IS NOT NULL AND verification_expires_at IS NOT NULL AND verification_expires_at > decided_at)
        OR (status = 'rejected' AND submitted_at IS NOT NULL AND decided_by_identity_id IS NOT NULL AND decided_at IS NOT NULL AND decision_reason IS NOT NULL AND verification_expires_at IS NULL)
        OR (status = 'superseded' AND submitted_at IS NOT NULL AND decided_by_identity_id IS NOT NULL AND decided_at IS NOT NULL AND decision_reason IS NOT NULL AND verification_expires_at IS NOT NULL)
      )
    );
    CREATE UNIQUE INDEX IF NOT EXISTS organization_verification_open_unique_idx
      ON fractal.organization_verification_requests (organization_id)
      WHERE status IN ('draft', 'submitted', 'under_review');
    CREATE INDEX IF NOT EXISTS organization_verification_review_queue_idx
      ON fractal.organization_verification_requests (submitted_at, id)
      WHERE status IN ('submitted', 'under_review');

    CREATE TABLE IF NOT EXISTS fractal.organization_beneficial_owner_declarations (
      id UUID PRIMARY KEY,
      verification_request_id UUID NOT NULL REFERENCES fractal.organization_verification_requests(id),
      owner_type TEXT NOT NULL CHECK (owner_type IN ('natural_person', 'legal_entity')),
      legal_name TEXT NOT NULL CHECK (length(legal_name) BETWEEN 2 AND 240),
      ownership_bps INTEGER NOT NULL CHECK (ownership_bps BETWEEN 0 AND 10000),
      is_control_person BOOLEAN NOT NULL DEFAULT false,
      nationality_or_jurisdiction_code VARCHAR(2) NOT NULL CHECK (nationality_or_jurisdiction_code ~ '^[A-Z]{2}$'),
      country_of_residence_code VARCHAR(2) CHECK (country_of_residence_code IS NULL OR country_of_residence_code ~ '^[A-Z]{2}$'),
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT organization_beneficial_owner_natural_residence CHECK (
        owner_type <> 'natural_person' OR country_of_residence_code IS NOT NULL
      )
    );
    CREATE INDEX IF NOT EXISTS organization_beneficial_owner_request_idx
      ON fractal.organization_beneficial_owner_declarations (verification_request_id, id);

    CREATE TABLE IF NOT EXISTS fractal.organization_verification_request_evidence (
      verification_request_id UUID NOT NULL,
      organization_id UUID NOT NULL REFERENCES fractal.organizations(id),
      evidence_document_id UUID NOT NULL,
      evidence_type TEXT NOT NULL CHECK (evidence_type IN ('registration_evidence', 'registry_extract', 'registered_address', 'ownership_structure', 'representative_authority', 'tax_registration', 'other')),
      PRIMARY KEY (verification_request_id, evidence_document_id),
      FOREIGN KEY (verification_request_id, organization_id)
        REFERENCES fractal.organization_verification_requests(id, organization_id),
      FOREIGN KEY (evidence_document_id, organization_id, evidence_type)
        REFERENCES fractal.organization_verification_evidence_documents(id, organization_id, evidence_type)
    );
    CREATE INDEX IF NOT EXISTS organization_verification_request_evidence_type_idx
      ON fractal.organization_verification_request_evidence (verification_request_id, evidence_type);

    CREATE OR REPLACE FUNCTION fractal.guard_organization_verification_submission()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      owner_count INTEGER;
      ownership_total INTEGER;
      control_count INTEGER;
      registration_evidence_count INTEGER;
      ownership_evidence_count INTEGER;
      authority_evidence_count INTEGER;
    BEGIN
      IF OLD.status = 'draft' AND NEW.status = 'submitted' THEN
        SELECT COUNT(*), COALESCE(SUM(ownership_bps), 0), COUNT(*) FILTER (WHERE is_control_person)
          INTO owner_count, ownership_total, control_count
          FROM fractal.organization_beneficial_owner_declarations
         WHERE verification_request_id = NEW.id;
        SELECT
          COUNT(*) FILTER (WHERE evidence_type = 'registration_evidence'),
          COUNT(*) FILTER (WHERE evidence_type = 'ownership_structure'),
          COUNT(*) FILTER (WHERE evidence_type = 'representative_authority')
          INTO registration_evidence_count, ownership_evidence_count, authority_evidence_count
          FROM fractal.organization_verification_request_evidence
         WHERE verification_request_id = NEW.id;
        IF owner_count = 0 OR ownership_total <> 10000 OR control_count = 0 THEN
          RAISE EXCEPTION 'organization verification requires complete ownership and at least one control person';
        END IF;
        IF registration_evidence_count = 0 OR ownership_evidence_count = 0 OR authority_evidence_count = 0 THEN
          RAISE EXCEPTION 'organization verification requires registration, ownership, and representative-authority evidence';
        END IF;
      ELSIF OLD.status IN ('approved', 'rejected', 'superseded') THEN
        IF NOT (OLD.status = 'approved' AND NEW.status = 'superseded') OR
           NEW.legal_name IS DISTINCT FROM OLD.legal_name OR
           NEW.registration_number IS DISTINCT FROM OLD.registration_number OR
           NEW.jurisdiction_code IS DISTINCT FROM OLD.jurisdiction_code OR
           NEW.entity_type IS DISTINCT FROM OLD.entity_type OR
           NEW.primary_activity IS DISTINCT FROM OLD.primary_activity OR
           NEW.registered_address IS DISTINCT FROM OLD.registered_address OR
           NEW.representative_authority_basis IS DISTINCT FROM OLD.representative_authority_basis OR
           NEW.submitted_by_identity_id IS DISTINCT FROM OLD.submitted_by_identity_id OR
           NEW.submitted_at IS DISTINCT FROM OLD.submitted_at OR
           NEW.decided_by_identity_id IS DISTINCT FROM OLD.decided_by_identity_id OR
           NEW.decided_at IS DISTINCT FROM OLD.decided_at OR
           NEW.decision_reason IS DISTINCT FROM OLD.decision_reason OR
           NEW.verification_expires_at IS DISTINCT FROM OLD.verification_expires_at THEN
          RAISE EXCEPTION 'terminal organization verification decision is immutable';
        END IF;
      ELSIF OLD.status <> 'draft' AND (
        NEW.legal_name IS DISTINCT FROM OLD.legal_name OR
        NEW.registration_number IS DISTINCT FROM OLD.registration_number OR
        NEW.jurisdiction_code IS DISTINCT FROM OLD.jurisdiction_code OR
        NEW.entity_type IS DISTINCT FROM OLD.entity_type OR
        NEW.primary_activity IS DISTINCT FROM OLD.primary_activity OR
        NEW.registered_address IS DISTINCT FROM OLD.registered_address OR
        NEW.representative_authority_basis IS DISTINCT FROM OLD.representative_authority_basis OR
        NEW.submitted_by_identity_id IS DISTINCT FROM OLD.submitted_by_identity_id OR
        NEW.submitted_at IS DISTINCT FROM OLD.submitted_at
      ) THEN
        RAISE EXCEPTION 'submitted organization verification facts are immutable';
      END IF;
      RETURN NEW;
    END;
    $$;
    DROP TRIGGER IF EXISTS organization_verification_submission_guard ON fractal.organization_verification_requests;
    CREATE TRIGGER organization_verification_submission_guard
      BEFORE UPDATE ON fractal.organization_verification_requests
      FOR EACH ROW EXECUTE FUNCTION fractal.guard_organization_verification_submission();

    CREATE OR REPLACE FUNCTION fractal.reject_organization_verification_child_mutation()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      RAISE EXCEPTION 'organization verification evidence and declarations are immutable';
    END;
    $$;
    DROP TRIGGER IF EXISTS organization_verification_evidence_immutable ON fractal.organization_verification_evidence_documents;
    CREATE TRIGGER organization_verification_evidence_immutable
      BEFORE UPDATE OR DELETE ON fractal.organization_verification_evidence_documents
      FOR EACH ROW EXECUTE FUNCTION fractal.reject_organization_verification_child_mutation();
    DROP TRIGGER IF EXISTS organization_beneficial_owner_immutable ON fractal.organization_beneficial_owner_declarations;
    CREATE TRIGGER organization_beneficial_owner_immutable
      BEFORE UPDATE OR DELETE ON fractal.organization_beneficial_owner_declarations
      FOR EACH ROW EXECUTE FUNCTION fractal.reject_organization_verification_child_mutation();
    DROP TRIGGER IF EXISTS organization_verification_request_evidence_immutable ON fractal.organization_verification_request_evidence;
    CREATE TRIGGER organization_verification_request_evidence_immutable
      BEFORE UPDATE OR DELETE ON fractal.organization_verification_request_evidence
      FOR EACH ROW EXECUTE FUNCTION fractal.reject_organization_verification_child_mutation();

    ALTER TABLE fractal.organization_invitations
      ALTER COLUMN token_hash DROP NOT NULL,
      ADD COLUMN IF NOT EXISTS accepted_by_identity_id UUID REFERENCES fractal.identities(id),
      ADD COLUMN IF NOT EXISTS revoked_by_identity_id UUID REFERENCES fractal.identities(id),
      ADD COLUMN IF NOT EXISTS revocation_reason TEXT,
      ADD COLUMN IF NOT EXISTS delivery_status TEXT,
      ADD COLUMN IF NOT EXISTS delivery_attempts INTEGER NOT NULL DEFAULT 0,
      ADD COLUMN IF NOT EXISTS delivery_claimed_at TIMESTAMPTZ,
      ADD COLUMN IF NOT EXISTS delivery_claimed_by TEXT,
      ADD COLUMN IF NOT EXISTS delivery_next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      ADD COLUMN IF NOT EXISTS delivery_sent_at TIMESTAMPTZ,
      ADD COLUMN IF NOT EXISTS delivery_terminal_at TIMESTAMPTZ,
      ADD COLUMN IF NOT EXISTS delivery_last_error TEXT,
      ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

    UPDATE fractal.organization_invitations
       SET accepted_by_identity_id = COALESCE(accepted_by_identity_id, CASE WHEN accepted_at IS NOT NULL THEN invited_by_identity_id END),
           revoked_by_identity_id = COALESCE(revoked_by_identity_id, CASE WHEN revoked_at IS NOT NULL THEN invited_by_identity_id END),
           revocation_reason = COALESCE(revocation_reason, CASE WHEN revoked_at IS NOT NULL THEN 'Legacy invitation revocation' END),
           delivery_status = COALESCE(delivery_status, CASE WHEN revoked_at IS NOT NULL THEN 'cancelled' ELSE 'sent' END),
           delivery_sent_at = COALESCE(delivery_sent_at, CASE WHEN token_hash IS NOT NULL THEN created_at END)
     WHERE accepted_at IS NOT NULL OR revoked_at IS NOT NULL OR delivery_status IS NULL;

    ALTER TABLE fractal.organization_invitations
      ALTER COLUMN delivery_status SET NOT NULL,
      ALTER COLUMN delivery_status SET DEFAULT 'requested',
      DROP CONSTRAINT IF EXISTS organization_invitations_terminal_exclusive,
      ADD CONSTRAINT organization_invitations_terminal_exclusive CHECK (accepted_at IS NULL OR revoked_at IS NULL),
      DROP CONSTRAINT IF EXISTS organization_invitations_acceptance_shape,
      ADD CONSTRAINT organization_invitations_acceptance_shape CHECK ((accepted_at IS NULL) = (accepted_by_identity_id IS NULL)),
      DROP CONSTRAINT IF EXISTS organization_invitations_revocation_shape,
      ADD CONSTRAINT organization_invitations_revocation_shape CHECK (
        (revoked_at IS NULL AND revoked_by_identity_id IS NULL AND revocation_reason IS NULL)
        OR (revoked_at IS NOT NULL AND revoked_by_identity_id IS NOT NULL AND length(revocation_reason) BETWEEN 5 AND 1000)
      ),
      DROP CONSTRAINT IF EXISTS organization_invitations_delivery_status_check,
      ADD CONSTRAINT organization_invitations_delivery_status_check CHECK (delivery_status IN ('requested', 'failed', 'sent', 'terminal', 'cancelled')),
      DROP CONSTRAINT IF EXISTS organization_invitations_delivery_attempts_check,
      ADD CONSTRAINT organization_invitations_delivery_attempts_check CHECK (delivery_attempts >= 0),
      DROP CONSTRAINT IF EXISTS organization_invitations_delivery_shape,
      ADD CONSTRAINT organization_invitations_delivery_shape CHECK (
        (delivery_status = 'sent' AND token_hash IS NOT NULL AND delivery_sent_at IS NOT NULL AND delivery_terminal_at IS NULL)
        OR (delivery_status = 'terminal' AND delivery_terminal_at IS NOT NULL AND delivery_sent_at IS NULL)
        OR (delivery_status = 'cancelled' AND delivery_claimed_at IS NULL AND delivery_claimed_by IS NULL)
        OR (delivery_status IN ('requested', 'failed') AND delivery_sent_at IS NULL AND delivery_terminal_at IS NULL)
      );

    CREATE INDEX IF NOT EXISTS organization_invitation_delivery_pending_idx
      ON fractal.organization_invitations (delivery_next_attempt_at, created_at, id)
      WHERE delivery_status IN ('requested', 'failed') AND accepted_at IS NULL AND revoked_at IS NULL;

    CREATE OR REPLACE FUNCTION fractal.guard_last_active_organization_owner()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      remaining_owners INTEGER;
      target_organization_id UUID;
    BEGIN
      target_organization_id := OLD.organization_id;
      IF OLD.role = 'owner' AND OLD.status = 'active' AND OLD.revoked_at IS NULL
         AND (TG_OP = 'DELETE' OR NEW.role <> 'owner' OR NEW.status <> 'active' OR NEW.revoked_at IS NOT NULL) THEN
        PERFORM pg_advisory_xact_lock(hashtextextended(target_organization_id::text, 0));
        SELECT COUNT(*) INTO remaining_owners
          FROM fractal.organization_memberships
         WHERE organization_id = target_organization_id
           AND id <> OLD.id
           AND role = 'owner'
           AND status = 'active'
           AND revoked_at IS NULL;
        IF remaining_owners = 0 THEN
          RAISE EXCEPTION 'organization must retain at least one active owner';
        END IF;
      END IF;
      RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
    END;
    $$;
    DROP TRIGGER IF EXISTS organization_membership_last_owner_guard ON fractal.organization_memberships;
    CREATE TRIGGER organization_membership_last_owner_guard
      BEFORE UPDATE OR DELETE ON fractal.organization_memberships
      FOR EACH ROW EXECUTE FUNCTION fractal.guard_last_active_organization_owner();
  `,
};
