import { randomUUID } from "node:crypto";
import type { PoolClient } from "pg";
import { requirePostgres, withPostgresTransaction } from "../db/postgres.js";
import { offeringNoticeCategories, parseOfferingNoticePolicy, type OfferingNoticeCategory } from "../modules/offerings/domain/offering-notice-policy.js";
import { appendPostgresAuditEvent } from "./postgres-audit.js";
import { appendOutboxEvent } from "./postgres-outbox.js";
import { readActivePlatformConfigurationForBinding } from "./postgres-platform-configuration.js";

export { offeringNoticeCategories };
export class OfferingNoticeError extends Error { constructor(message:string,readonly code:"not_found"|"forbidden"|"conflict"|"invalid_input"|"policy_unavailable"){super(message);this.name="OfferingNoticeError";} }

type RequestRow={id:string;reference:string;organization_id:string;offering_id:string;public_reference:string;offering_name:string;category:OfferingNoticeCategory;subject:string;body:string;policy_version_id:string;policy_reference:string;policy_name:string;policy_jurisdiction_code:string;policy_legal_basis_reference:string;retention_days:number;acknowledgment_required:boolean;acknowledgment_window_days:number|null;status:"submitted"|"approved"|"rejected";submitted_by_identity_id:string;submitter_name:string;submitted_at:Date;reviewed_by_identity_id:string|null;reviewer_name:string|null;reviewed_at:Date|null;decision_reason:string|null;published_notice_id:string|null;audience_count:number|null;retain_until:Date|null;acknowledgment_due_at:Date|null;read_count:string;acknowledged_count:string};
type RecipientRow={notice_id:string;organization_name:string;public_reference:string;offering_name:string;category:OfferingNoticeCategory;subject:string;body:string;policy_reference:string;policy_legal_basis_reference:string;retain_until:Date;acknowledgment_required:boolean;acknowledgment_due_at:Date|null;published_at:Date;first_read_at:Date|null;acknowledged_at:Date|null};
const lockKey=4_182_901_520;
async function lock(client:PoolClient){await client.query("SELECT pg_advisory_xact_lock($1)",[lockKey]);}
function clean(value:string,label:string,min:number,max:number){const result=value.trim();if(result.length<min||result.length>max)throw new OfferingNoticeError(`${label} must contain ${min} to ${max} characters.`,"invalid_input");return result;}
function ref(){return `ONR-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${randomUUID().replaceAll("-","").slice(0,8).toUpperCase()}`;}
function offeringName(terms:unknown,reference:string){if(terms&&typeof terms==="object"){const value=(terms as Record<string,unknown>).name;if(typeof value==="string"&&value.trim())return value.trim();}return reference;}

async function authority(client:PoolClient,organizationId:string,category?:OfferingNoticeCategory){
  const organization=await client.query<{jurisdiction_code:string|null}>("SELECT jurisdiction_code FROM fractal.organizations WHERE id=$1",[organizationId]);
  if(!organization.rows[0])throw new OfferingNoticeError("Organization not found.","not_found");const jurisdictionCode=organization.rows[0].jurisdiction_code;
  if(!jurisdictionCode)throw new OfferingNoticeError("Notice creation is unavailable until the organization has an approved jurisdiction.","policy_unavailable");
  const binding=await readActivePlatformConfigurationForBinding(client,"offering.notice.policy");if(!binding)throw new OfferingNoticeError("Notice creation is unavailable until an approved offering-notice policy is active.","policy_unavailable");
  const policy=parseOfferingNoticePolicy(binding.value);const jurisdiction=policy.jurisdictions[jurisdictionCode];if(!jurisdiction)throw new OfferingNoticeError(`The active offering-notice policy does not cover ${jurisdictionCode}.`,"policy_unavailable");
  return{binding,policy,jurisdiction,jurisdictionCode,rule:category?jurisdiction.rules[category]:null};
}

export async function getOfferingNoticePolicyOptions(organizationId:string){return withPostgresTransaction(async client=>{const value=await authority(client,organizationId);return{policy:{versionId:value.binding.versionId,versionNumber:value.binding.versionNumber,reference:value.policy.policyReference,name:value.policy.policyName,schemaVersion:value.policy.schemaVersion,jurisdictionCode:value.jurisdictionCode,legalBasisReference:value.jurisdiction.legalBasisReference},rules:offeringNoticeCategories.map(category=>({category,...value.jurisdiction.rules[category]}))};});}

const requestSelect=`SELECT request.*,product.public_reference,version.terms,submitter.legal_name AS submitter_name,reviewer.legal_name AS reviewer_name,notice.audience_count,notice.retain_until,notice.acknowledgment_due_at,
  count(recipient.first_read_at)::text AS read_count,count(recipient.acknowledged_at)::text AS acknowledged_count
  FROM fractal.offering_notice_requests request JOIN fractal.offering_products product ON product.id=request.offering_id
  JOIN LATERAL(SELECT terms FROM fractal.offering_publication_versions WHERE offering_id=product.id ORDER BY version DESC LIMIT 1) version ON true
  JOIN fractal.identities submitter ON submitter.id=request.submitted_by_identity_id LEFT JOIN fractal.identities reviewer ON reviewer.id=request.reviewed_by_identity_id
  LEFT JOIN fractal.offering_notices notice ON notice.id=request.published_notice_id LEFT JOIN fractal.offering_notice_recipients recipient ON recipient.notice_id=notice.id`;
function mapRequest(row:RequestRow&{terms?:unknown}){return{id:row.id,reference:row.reference,organizationId:row.organization_id,offeringId:row.offering_id,publicReference:row.public_reference,offeringName:offeringName(row.terms,row.public_reference),category:row.category,subject:row.subject,body:row.body,status:row.status,policy:{versionId:row.policy_version_id,reference:row.policy_reference,name:row.policy_name,jurisdictionCode:row.policy_jurisdiction_code,legalBasisReference:row.policy_legal_basis_reference,retentionDays:row.retention_days},acknowledgment:{required:row.acknowledgment_required,windowDays:row.acknowledgment_window_days,dueAt:row.acknowledgment_due_at?.toISOString()??null},submittedBy:{id:row.submitted_by_identity_id,legalName:row.submitter_name},submittedAt:row.submitted_at.toISOString(),reviewedBy:row.reviewed_by_identity_id&&row.reviewer_name?{id:row.reviewed_by_identity_id,legalName:row.reviewer_name}:null,reviewedAt:row.reviewed_at?.toISOString()??null,decisionReason:row.decision_reason,publishedNoticeId:row.published_notice_id,audienceCount:row.audience_count,retainUntil:row.retain_until?.toISOString()??null,readCount:Number(row.read_count),acknowledgedCount:Number(row.acknowledged_count)};}

export async function listOfferingNoticeRequests(organizationId:string){const result=await requirePostgres().query<RequestRow&{terms:unknown}>(`${requestSelect} WHERE request.organization_id=$1 GROUP BY request.id,product.id,version.terms,submitter.id,reviewer.id,notice.id ORDER BY request.submitted_at DESC,request.id DESC`,[organizationId]);return result.rows.map(mapRequest);}
export async function getOfferingNoticeRequest(requestId:string){const result=await requirePostgres().query<RequestRow&{terms:unknown}>(`${requestSelect} WHERE request.id=$1 GROUP BY request.id,product.id,version.terms,submitter.id,reviewer.id,notice.id`,[requestId]);return result.rows[0]?mapRequest(result.rows[0]):null;}

export async function submitOfferingNotice(input:{organizationId:string;offeringId:string;category:OfferingNoticeCategory;subject:string;body:string;actorIdentityId:string;commandKey:string}){
  return withPostgresTransaction(async client=>{await lock(client);const subject=clean(input.subject,"Subject",5,240),body=clean(input.body,"Message",20,12000),commandKey=clean(input.commandKey,"Command key",1,200);
    const replay=await client.query<{id:string;offering_id:string;category:string;subject:string;body:string}>("SELECT id,offering_id,category,subject,body FROM fractal.offering_notice_requests WHERE submitted_by_identity_id=$1 AND command_key=$2",[input.actorIdentityId,commandKey]);
    if(replay.rows[0]){const row=replay.rows[0];if(row.offering_id!==input.offeringId||row.category!==input.category||row.subject!==subject||row.body!==body)throw new OfferingNoticeError("This command key was already used for different notice content.","conflict");return{requestId:row.id,replayed:true};}
    const product=await client.query<{organization_id:string}>("SELECT organization_id FROM fractal.offering_products WHERE id=$1 AND status IN('published','paused','closed')",[input.offeringId]);if(!product.rows[0])throw new OfferingNoticeError("Published offering not found.","not_found");if(product.rows[0].organization_id!==input.organizationId)throw new OfferingNoticeError("Offering does not belong to this organization.","forbidden");
    const auth=await authority(client,input.organizationId,input.category);const id=randomUUID(),rule=auth.rule!;
    await client.query(`INSERT INTO fractal.offering_notice_requests(id,reference,organization_id,offering_id,category,subject,body,policy_version_id,policy_version_number,policy_projection_version,policy_value_sha256,policy_reference,policy_name,policy_schema_version,policy_jurisdiction_code,policy_legal_basis_reference,retention_days,acknowledgment_required,acknowledgment_window_days,command_key,submitted_by_identity_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21)`,[id,ref(),input.organizationId,input.offeringId,input.category,subject,body,auth.binding.versionId,auth.binding.versionNumber,auth.binding.projectionVersion,auth.binding.valueSha256,auth.policy.policyReference,auth.policy.policyName,auth.policy.schemaVersion,auth.jurisdictionCode,auth.jurisdiction.legalBasisReference,rule.retentionDays,rule.acknowledgmentRequired,rule.acknowledgmentWindowDays,commandKey,input.actorIdentityId]);
    const audit=await appendPostgresAuditEvent(client,{scopeKey:`organization:${input.organizationId}`,organizationId:input.organizationId,actorId:input.actorIdentityId,actorType:"user",action:"offering.notice.submitted",entityType:"offering_notice_request",entityId:id,payload:{offeringId:input.offeringId,category:input.category,policyVersionId:auth.binding.versionId}});await appendOutboxEvent(client,{aggregateType:"offering_notice_request",aggregateId:id,eventType:"offering.notice.submitted",payload:{organizationId:input.organizationId,offeringId:input.offeringId,auditEventId:audit.id}});return{requestId:id,replayed:false};
  });
}

export async function decideOfferingNotice(input:{requestId:string;actorIdentityId:string;decision:"approve"|"reject";decisionReason:string}){return withPostgresTransaction(async client=>{await lock(client);const reason=clean(input.decisionReason,"Decision reason",20,2000);const result=await client.query<RequestRow>("SELECT * FROM fractal.offering_notice_requests WHERE id=$1 FOR UPDATE",[input.requestId]);const request=result.rows[0];if(!request)throw new OfferingNoticeError("Offering notice request not found.","not_found");const desired=input.decision==="approve"?"approved":"rejected";if(request.status!=="submitted"){if(request.status===desired)return{requestId:request.id,status:request.status,publishedNoticeId:request.published_notice_id,replayed:true};throw new OfferingNoticeError("This notice request already has a different terminal decision.","conflict");}if(request.submitted_by_identity_id===input.actorIdentityId)throw new OfferingNoticeError("The submitter cannot decide the same notice request.","forbidden");const now=new Date();let noticeId:string|null=null,audienceCount=0;
  if(input.decision==="approve"){const recipients=await client.query<{id:string;investor_identity_id:string}>(`SELECT DISTINCT ON(investor_identity_id) id,investor_identity_id FROM fractal.investment_reservations WHERE offering_id=$1 AND status='confirmed' ORDER BY investor_identity_id,created_at DESC,id DESC`,[request.offering_id]);if(!recipients.rowCount)throw new OfferingNoticeError("A notice cannot be published until at least one confirmed investor is in its frozen audience.","conflict");noticeId=randomUUID();audienceCount=recipients.rowCount??0;const retainUntil=new Date(now.getTime()+request.retention_days*86_400_000);const due=request.acknowledgment_required?new Date(now.getTime()+request.acknowledgment_window_days!*86_400_000):null;
    await client.query(`INSERT INTO fractal.offering_notices(id,request_id,organization_id,offering_id,category,subject,body,audience_type,policy_version_id,policy_reference,policy_jurisdiction_code,policy_legal_basis_reference,retention_days,retain_until,acknowledgment_required,acknowledgment_due_at,audience_count,published_by_identity_id,published_at) VALUES($1,$2,$3,$4,$5,$6,$7,'confirmed_investors',$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18)`,[noticeId,request.id,request.organization_id,request.offering_id,request.category,request.subject,request.body,request.policy_version_id,request.policy_reference,request.policy_jurisdiction_code,request.policy_legal_basis_reference,request.retention_days,retainUntil,request.acknowledgment_required,due,audienceCount,input.actorIdentityId,now]);
    for(const recipient of recipients.rows)await client.query("INSERT INTO fractal.offering_notice_recipients(id,notice_id,investor_identity_id,source_reservation_id,made_available_at) VALUES($1,$2,$3,$4,$5)",[randomUUID(),noticeId,recipient.investor_identity_id,recipient.id,now]);}
  await client.query("UPDATE fractal.offering_notice_requests SET status=$2,reviewed_by_identity_id=$3,reviewed_at=$4,decision_reason=$5,published_notice_id=$6 WHERE id=$1",[request.id,desired,input.actorIdentityId,now,reason,noticeId]);const audit=await appendPostgresAuditEvent(client,{scopeKey:`organization:${request.organization_id}`,organizationId:request.organization_id,actorId:input.actorIdentityId,actorType:"user",action:`offering.notice.${desired}`,entityType:"offering_notice_request",entityId:request.id,reason,payload:{offeringId:request.offering_id,publishedNoticeId:noticeId,audienceCount}});await appendOutboxEvent(client,{aggregateType:"offering_notice_request",aggregateId:request.id,eventType:`offering.notice.${desired}`,payload:{organizationId:request.organization_id,offeringId:request.offering_id,publishedNoticeId:noticeId,audienceCount,auditEventId:audit.id}});return{requestId:request.id,status:desired,publishedNoticeId:noticeId,replayed:false};});}

export async function listInvestorOfferingNotices(investorIdentityId:string){const result=await requirePostgres().query<RecipientRow>(`SELECT notice.id AS notice_id,organization.legal_name AS organization_name,product.public_reference,version.terms,notice.category,notice.subject,notice.body,notice.policy_reference,notice.policy_legal_basis_reference,notice.retain_until,notice.acknowledgment_required,notice.acknowledgment_due_at,notice.published_at,recipient.first_read_at,recipient.acknowledged_at FROM fractal.offering_notice_recipients recipient JOIN fractal.offering_notices notice ON notice.id=recipient.notice_id JOIN fractal.organizations organization ON organization.id=notice.organization_id JOIN fractal.offering_products product ON product.id=notice.offering_id JOIN LATERAL(SELECT terms FROM fractal.offering_publication_versions WHERE offering_id=product.id ORDER BY version DESC LIMIT 1) version ON true WHERE recipient.investor_identity_id=$1 ORDER BY notice.published_at DESC,notice.id DESC`,[investorIdentityId]);return result.rows.map(row=>({id:row.notice_id,organizationName:row.organization_name,publicReference:row.public_reference,offeringName:offeringName((row as RecipientRow&{terms:unknown}).terms,row.public_reference),category:row.category,subject:row.subject,body:row.body,policyReference:row.policy_reference,legalBasisReference:row.policy_legal_basis_reference,retainUntil:row.retain_until.toISOString(),acknowledgmentRequired:row.acknowledgment_required,acknowledgmentDueAt:row.acknowledgment_due_at?.toISOString()??null,publishedAt:row.published_at.toISOString(),firstReadAt:row.first_read_at?.toISOString()??null,acknowledgedAt:row.acknowledged_at?.toISOString()??null}));}

async function recipientEvent(input:{investorIdentityId:string;noticeId:string;eventType:"opened"|"acknowledged"}){return withPostgresTransaction(async client=>{const result=await client.query<{id:string;first_read_at:Date|null;acknowledged_at:Date|null;acknowledgment_required:boolean}>(`SELECT recipient.id,recipient.first_read_at,recipient.acknowledged_at,notice.acknowledgment_required FROM fractal.offering_notice_recipients recipient JOIN fractal.offering_notices notice ON notice.id=recipient.notice_id WHERE recipient.notice_id=$1 AND recipient.investor_identity_id=$2 FOR UPDATE OF recipient`,[input.noticeId,input.investorIdentityId]);const row=result.rows[0];if(!row)throw new OfferingNoticeError("Offering notice not found.","not_found");if(input.eventType==="acknowledged"&&!row.acknowledgment_required)throw new OfferingNoticeError("This notice does not require acknowledgment.","conflict");if(input.eventType==="acknowledged"&&!row.first_read_at)throw new OfferingNoticeError("Open the notice before acknowledging it.","conflict");const existing=input.eventType==="opened"?row.first_read_at:row.acknowledged_at;if(existing)return{noticeId:input.noticeId,replayed:true,occurredAt:existing.toISOString()};const now=new Date();await client.query("INSERT INTO fractal.offering_notice_recipient_events(id,recipient_id,event_type,actor_identity_id,occurred_at) VALUES($1,$2,$3,$4,$5)",[randomUUID(),row.id,input.eventType,input.investorIdentityId,now]);await client.query(`UPDATE fractal.offering_notice_recipients SET ${input.eventType==="opened"?"first_read_at":"acknowledged_at"}=$2 WHERE id=$1`,[row.id,now]);return{noticeId:input.noticeId,replayed:false,occurredAt:now.toISOString()};});}
export function markInvestorOfferingNoticeRead(investorIdentityId:string,noticeId:string){return recipientEvent({investorIdentityId,noticeId,eventType:"opened"});}
export function acknowledgeInvestorOfferingNotice(investorIdentityId:string,noticeId:string){return recipientEvent({investorIdentityId,noticeId,eventType:"acknowledged"});}
